### ISSUE TITLE
Enum definition type values not rendered

### ISSUE THREAD

**Issue by patvong** [Swagger2Markup/swagger2markup#111]
### Description
I have a swagger file with an enum definition as follow:
```
"WebhookResourceAction": {
  "type": "string",
  "title": "WebhookResourceAction",
  "enum": [
    "ADDED",
    "REMOVED",
    "CHANGED"
  ],
  "description": "Type of action on a resource<br/>\n- ADDED: A resource have been added<br/>\n- REMOVED: A resource have been removed<br/>\n- CHANGED: A resource have been changed"
}
```
On the master branch, the rendered `definitions.adoc` is this:
```
=== WebhookResourceAction
[%hardbreaks]
Type of action on a resource<br/>
- ADDED: A resource have been added<br/>
- REMOVED: A resource have been removed<br/>
- CHANGED: A resource have been changed

No Content
```
I think the related code is here: https://github.com/Swagger2Markup/swagger2markup/blob/master/src/main/java/io/github/swagger2markup/internal/document/builder/DefinitionsDocumentBuilder.java#L296
In my case, it should check for the enum values and not properties.

However in version 0.9.3, the definition is not rendered at all which is a **blocker** for us.
I wasn't able to track the issue since there is no v0.9.3 tag.
On v0.9.2 though, the issue seems to be here:https://github.com/Swagger2Markup/swagger2markup/blob/v0.9.2/src/main/java/io/github/robwin/swagger2markup/builder/document/DefinitionsDocument.java#L118
It looks like Swagger parser 1.0.13 doesn't parse the enum type vs the version 1.0.17 which is used in master.

I'd like to be able to render the enum description and a table of the different values, what do you suggest?

**Comment by RobWin** [comment]
Thx. We have a look at it.

**Comment by patvong** [comment]
@RobWin On v0.9.2 this is what it generates:
```
=== WebhookResourceAction
[options="header"]
|===
|Name|Description|Required|Schema|Default
|WebhookResourceAction|Type of action on a resource<br/>
- ADDED: A resource have been added<br/>
- REMOVED: A resource have been removed<br/>
- CHANGED: A resource have been changed|false|enum (ADDED, REMOVED, CHANGED)|
|===
```

**Comment by RobWin** [comment]
Does that work for you as a workaround?

**Comment by patvong** [comment]
Yes works for me at the moment. Thanks!

**Comment by RobWin** [comment]
You can move the description from the property into the object.
