### ISSUE TITLE
Migrate Swagger2Markup to Java8

### ISSUE THREAD

**Issue by RobWin** [Swagger2Markup/swagger2markup#112]
What do the users of Swagger2Markup think about it?

**Comment by erikhakansson** [comment]
Preferably not.
We run Swagger2Markup in production that runs on Java 7. Java 8 migration is on the roadmap but it won't happen for a while.
We could of course continue to run on the current version for now, but there seems to be a lot of nice things coming in 1.0.

**Comment by erikhakansson** [comment]
Actually, our Java 8 migration will happen sooner than planned so I'm all for Java 8 migration of Swagger2Markup!

**Comment by RobWin** [comment]
Nice :D

**Comment by RobWin** [comment]
Done. V1.0.0 requires java8 now.
