### ISSUE TITLE
Display model properties as JSON Schema instead of table

### ISSUE THREAD

**Issue by rathishkumar89** [Swagger2Markup/swagger2markup#118]
I have the ASCII format of swagger.json when i convert the file to PDF using Asciidoctorj it displays all the schema in table format is it possible to get it in JSON Schema itself? Could you provide me with some options if available?

**Comment by RobWin** [comment]
Hi, 

no, that's not possible, but if you have separate JSON Schema files, you could import the files and the content is displayed below the table.
Do you use the Maven/Gradle plugin or Swagger2Markup directly?

If you use and like Swagger2Markup, I would love to get your GitHub star.

**Comment by rathishkumar89** [comment]
Hi,
 I use maven Plugin .Will that be possible in swagger2Markup directly? Or will swagger2Markup supports this feature?

**Comment by RobWin** [comment]
See https://swagger2markup.readme.io/docs/maven-plugin

You can configure the `schemasDir` property to a folder path where your JSON Schema files reside. For example: `src/docs/schemas`

Swagger2Markup searches for Schema files which must be named like the definition model in your Swagger file.

For example: for a `Pet` definition, it searches for a `Pet.json` in your configured `schemasDir`.

**Comment by rathishkumar89** [comment]
i can produce an ASCII DOC but i get it 
https://github.com/rathishkumar89/swaggerAsciiTest/tree/fdb2577f80df47e9f0509e128cb5087951aed855/ascii-to-pdf/build/docs/asciidoc/generated/result.adoc

where i can see everything in table format .Instead is it possible to get the schema as it is? (like mentioned below) in the ASCII format?
https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore-simple.json

**Comment by RobWin** [comment]
Do you understand what I have written the comment above?
