### ISSUE TITLE
(AsciiDoc) Control characters in input are not escaped

### ISSUE THREAD

**Issue by noschinl** [Swagger2Markup/swagger2markup#126]
AsciiDoc control characters in a swagger.json file are not escaped. I.e., a file containing the description

```
"description": "A boolean expression. The | can be used for expressing disjunction. "
```

will contain this `|` character in the output, which breaks the generated AsciiDoc if it occurs in a table.

**Comment by RobWin** [comment]
Thx. We have a look at it.

**Comment by Kabhal** [comment]
I can't reproduce the problem, I tried to include some pipes in all descriptions in a JSON swagger, pipes are correctly escaped.
Could you provide a whole example to help to reproduce ?

**Comment by Kabhal** [comment]
Currently, markup-document-builder escape '|' in cells with '\|'.
Perhaps your tool which later convert your AsciiDoc does not support this escaping ..
For example, I know an alternative is to use '{vbar}' to escape pipes.

**Comment by RobWin** [comment]
I guess he uses S2M v0.9.2 which is not that smart as v1.0.0-SNAPSHOT.

**Comment by RobWin** [comment]
We should add the github issue template file which ask users to specify the version they use.

**Comment by RobWin** [comment]
@noschinl Can you test 1.0.0-SNAPSHOT if it solved your issue?
See docs: http://swagger2markup.github.io/swagger2markup/1.0.0-SNAPSHOT
