### ISSUE TITLE
Supplementing path documentation when separate adoc files are used

### ISSUE THREAD

**Issue by mattadamson** [Swagger2Markup/swagger2markup#127]
Team,

We like the feature which separate individual adoc files for each path. Whilst the content is derived from the underlying swagger API end point is there a way to supplement each adoc file with additional content in a specific placeholder. e.g. if we had a template path.adoc file for each generate path and a placeholder 

{additionalDocumentation}

We would like files referenced at a given location e.g. using the title of the path with a known format e.g. "login request" could look at a login_request sub folder and use a file called additionalDocumentation.adoc which if present would add content to this placeholder. 

This is similar to the way the examplesDirectory structure works. We could use this place holder for our technical authors perhaps to include additional supplementary information for each end point above and beyond the standard description / notes fields we use in the swagger annotations.

I saw the extensions SPI just introduced 

http://swagger2markup.github.io/swagger2markup/1.0.0-SNAPSHOT/#_pathsdocumentextension

so perhaps that would help? Although it seems a generic core feature useful 

Appreciate your thoughts?

**Comment by RobWin** [comment]
Hi,

please have a look at 
http://swagger2markup.github.io/swagger2markup/1.0.0-SNAPSHOT/#_extensions_points
and the provided file import extension:
http://swagger2markup.github.io/swagger2markup/1.0.0-SNAPSHOT/#_dynamic_file_import_extension

Is that sufficient for you?

**Comment by RobWin** [comment]
Would love to get your GitHub Star on the core project :)

**Comment by mattadamson** [comment]
Thanks Robert,

The dynamic file import extension certainly does look like it could help here. The documentation is quite detailed although I'm not clear on exactly how to configure. It might be useful adding an example project at some point showing them being used. 

It mentions using place holders such as 

document-before-*.<markup.ext>

Does * here imply the exact character for the file or any content? For adhoc files should <markup.ext> be simply adoc? 

For example consider the project swagger2markup-maven-project-template which uses the pet store API with operation adoc files generated such as createUser.adoc

If we want to add content to supplement each path the place holder "operation-begin-*.<markup.ext>" seems appropriate.  Should we create a file called operation-begin-*.adoc  in the folder specified by the config property swagger2markup.extensions.dynamicPaths.contentPath. However this name implies the same content for all paths.  Does the * here mean it should be named "operation-begin-createUser.adoc" ?

Thanks

**Comment by RobWin** [comment]
We update the documentation to make it more clear.

**Comment by RobWin** [comment]
The files must be placed into a folder which is equal to the `operationId` of the path operation.
Lets say `swagger2markup.extensions.dynamicPaths.contentPath = /tmp"

You must place the file into a folder called `/tmp/<operationId>`

The `operationId` is explained here: http://swagger2markup.github.io/swagger2markup/1.0.0-SNAPSHOT/#_swagger_operationid

Lets say the `operationId` is `updatePet`, you need

`/tmp/updatePet/operation-begin-nameisnotimportant.adoc `

**Comment by mattadamson** [comment]
thanks that worked

**Comment by mattadamson** [comment]
I was considering opening a new issue however this query is very closely related it's better if we reopen and work through. I also tried supplementing a model definition and from 

http://swagger2markup.github.io/swagger2markup/1.0.0-SNAPSHOT/#_maven_plugin

we see

"Definitions extensions, relatively to each extension contentPath :
DEFINITION_BEFORE : <definitionName>/definition-before-*.<markup.ext>"

Here I used the same folder configured with swagger2markup.extensions.dynamicPaths.contentPath and created a folder for the definition e.g. ModelA and within that folder I copied a file definition-before.adoc with some text.  This didn't appear to be sustituted at runtime. 

Any thoughts why? Thanks

**Comment by RobWin** [comment]
Please have a look at https://github.com/Swagger2Markup/swagger2markup-maven-project-template/blob/s2m-1.0.0/pom.xml

Did you configure it as follows: `<swagger2markup.extensions.dynamicPaths.contentPath>${project.basedir}/src/docs/asciidoc/extensions/paths</swagger2markup.extensions.dynamicPaths.contentPath>`

You must use `${project.basedir}` so that relative paths work correctly.
