### ISSUE TITLE
Multiple example request / responses

### ISSUE THREAD

**Issue by mattadamson** [Swagger2Markup/swagger2markup#128]
The examplesDirectory is  a useful feature we can use to provide an example request / response against each end point. However in some cases it would be really useful to provide multiple examples e.g. with a complex type that has a number of unique combinations for certain fields / use cases.  

Perhaps we could extend the framework to look up for numbered sequence files e.g. http-request_<sequenceno>.   If we had multiple examples the ordering could simply be used to indicate one response maps to a given request. 

Thoughts?

**Comment by RobWin** [comment]
Hi,

you could also use the dynamic file import extension for this requirement. You can create many htte-request files like this:

* operation-end-example1.adoc
* operation-end-example2.adoc

Each file contains an HTTP Request and Response example.

**Comment by RobWin** [comment]
But anyway its a good idea. Would you like to contribute and create a Pull Request?

**Comment by mattadamson** [comment]
Thanks Robert,  yes I can certainly look into that at some point although I'm not quite sure when.

**Comment by mattadamson** [comment]
Hi Robert, the exampleDirectory doesn't appear to work in the latest snapshot release. Am I missing something however we only see this configuration option now

swagger2markup.generatedExamplesEnabled

**Comment by RobWin** [comment]
It has been moved into an extension:

Please have a look at: http://swagger2markup.github.io/swagger2markup/1.0.0-SNAPSHOT/#extension_spring_restdocs

**Comment by mattadamson** [comment]
thanks. We don't actually use spring so perhaps the name isn't ideal however I understand this feature also has some spring rest specifc integration e.g. generating snippets?

However I tried 

						<swagger2markup.extensions.springRestDocs.snippetBaseUri>${project.basedir}/src/docs/exampleDocs</swagger2markup.extensions.springRestDocs.snippetBaseUri>
						<swagger2markup.extensions.springRestDocs.defaultSnippets>false</swagger2markup.extensions.springRestDocs.defaultSnippets>

It didn't seem to pick up any adoc files

**Comment by RobWin** [comment]
How did you name your files?
`swagger2markup.extensions.springRestDocs.defaultSnippets` should be `true`

Then call your files 
```
<operationId>/http-request.<markup.ext>
<operationId>/http-response.<markup.ext>
<operationId>/curl-request.<markup.ext>
```

For example: 
`addPet/http-request.adoc`

**Comment by mattadamson** [comment]
I created a sub folder under that path with the operationId and named them http-request.adoc / http-response.adoc.  I also tried setting defaultSnippets to true with the same issue. However I set to false initially as the helps indicates

"Boolean value. Set to false to disable default snippet files"

I assumed this meant default snippet files wouldn't be auto generated. "default" here maybe confusing as nothing is really defaulted.

I also tried changing this

						<swagger2markup.separatedOperationsEnabled>false</swagger2markup.separatedOperationsEnabled>

to both false / true with the same issue.

**Comment by RobWin** [comment]
Do you have an example project?

**Comment by mattadamson** [comment]
I don't easily however you should be able to reproduce this by simply modifying the default swagger2markup-maven-project-template and adding the two configuration options then creating a nested folder for one operation and the same adoc files. The HTML also doesn't contain any referenced examples

**Comment by RobWin** [comment]
How did you add the extension jar file to your maven pom.xml?

**Comment by mattadamson** [comment]
thanks including the extension jar resolved the issue.

**Comment by RobWin** [comment]
Where did you include it? Plugin dependencies?

**Comment by mattadamson** [comment]
yes exactly just a dependency within the plugin dependencies section
