### ISSUE TITLE
Custom extension issue building

### ISSUE THREAD

**Issue by mattadamson** [Swagger2Markup/swagger2markup#129]
I thought a custom extension could be a great way to supplement each path adoc file with dynamic data driven from the database using the operation id / context.

I tried using the example project swagger2markup-maven-project-template as a starting point and added the following dependency

		                <groupId>io.github.swagger2markup</groupId>
		                <artifactId>swagger2markup-import-files-ext</artifactId>
		                <version>1.0.0-SNAPSHOT</version>

However we see a build error because one of the dependencies 

markup-document-builder
1.0.0-SNAPSHOT

has a dependency

      <groupId>nl.jworks.markdown_to_asciidoc</groupId>
      <artifactId>markdown_to_asciidoc</artifactId>
      <version>1.0</version>

whch can't be found

Thoughts please?

**Comment by RobWin** [comment]
Unfortunately markdown_to_asciidoc is only available via JCentral. I asked them to publish the library in Maven Central. 

You have to add the repository to your pom.xml

```
<repositories>
    <repository>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
        <id>jcenter-releases</id>
        <name>jcenter</name>
        <url>http://jcenter.bintray.com</url>
    </repository>
</repositories>
```

**Comment by mattadamson** [comment]
thanks. Now it's building however now I'm getting an issue as the extension doesn't appear to be called. I've created an extension simply called ext defined as 

public class ext extends DefinitionsDocumentExtension {

I created a file io.github.swagger2markup.spi.DefinitionsDocumentExtension within the resources\META-INF\services folder which we see copied to the target/classes/META-INF/service folder. 

I added break points whilst debugging the maven plug in and also console statements neither of which appear to indicate it's loaded.

**Comment by RobWin** [comment]
Better use an upper case class name.
Could you please paste the content of the `io.github.swagger2markup.spi.DefinitionsDocumentExtension` file?
I must contain the name of your class including the package. For example `my.package.ext`

**Comment by mattadamson** [comment]
I changed the class to be named MyCustomExtension and included in the com.customext package. 

The file now only contains 

com.customext.MyCustomExtension

which still doesn't appear to load

**Comment by RobWin** [comment]
Could you please share your code? Do you use the Maven or Gradle Plugin?

**Comment by mattadamson** [comment]
sure I've attached the project. It's simply swagger2markup-maven-project-template with a few changes to add the extension and try and comfigure.
[MavenTestProject.zip](https://github.com/Swagger2Markup/swagger2markup/files/217297/MavenTestProject.zip)

**Comment by RobWin** [comment]
The extension must be a seperate project and build a jar file.
The extension jar file must be added to the plugin dependencies then:

I create an example tomorrow.

**Comment by mattadamson** [comment]
thanks Robert, I have this working now in a separate maven module.

**Comment by RobWin** [comment]
ok
