### ISSUE TITLE
Custom extensions for path definitions - providing more granularity 

### ISSUE THREAD

**Issue by mattadamson** [Swagger2Markup/swagger2markup#130]
I noticed the Position enum in PathsDocumentExtension currently provides

    public enum Position {
        DOCUMENT_BEFORE,
        DOCUMENT_AFTER,
        DOCUMENT_BEGIN,
        DOCUMENT_END,
        OPERATION_BEGIN,
        OPERATION_END
    }

However for us at least it would be useful to provide more control to inject content in the paths parameters definition at the start.  For example we have some generic name value structure which can actually be different based on the path operation. In this case we could supplement the parameters section with this additional content e.g. an ascii doc table in this case.

Even if we extended the enum to include other values such as OPERATION_PARAMETERS_BEGIN/END I couldn't see how we would indicate an offset which levelOffset returns to indicate the parameters section

Thoughts?

**Comment by Kabhal** [comment]
This can be done.
You'll have to take care about the content you inject, because parameters definitions are displayed in tables cells, so that you can't add too much content.

**Comment by Kabhal** [comment]
Typically, you should not inject tables, titles, etc .. (it won't even work) into this particular content.

**Comment by Kabhal** [comment]
To be sure about your request : you want to inject content in each parameter description, or before the parameters table ?

**Comment by mattadamson** [comment]
Thanks actually this is simply a new table with some text to supplement the existing content. I know we could use standard mark up builder table methods if we were hooked in at the right position

**Comment by Kabhal** [comment]
I start working on adding new begin/end positions for each subsections of different documents.

**Comment by Kabhal** [comment]
let's try with new positions, including OPERATION_PARAMETERS_BEGIN :)

**Comment by RobWin** [comment]
:+1:

**Comment by mattadamson** [comment]
Great work @Kabhal. I tried one of the values OPERATION_PARAMETERS_AFTER and it works fine
