### ISSUE TITLE
Clicking on model definitions in HTML doesn't navigate to the model 

### ISSUE THREAD

**Issue by mattadamson** [Swagger2Markup/swagger2markup#132]
This may not be a specific issue with the swagger to ascii doc conversion although I'm not sure where else to put it.  However I noticed when using swagger2markup and then ascii doctor to HTML through asciidoctor-maven-plugin the links to models added e.g. in the definitions section can't be navigated directly. 

For example if the operations section indicates a parameter of a specific type I would expect clicking on the link to jump to the definition

**Comment by Kabhal** [comment]
What are the configuration used ?
1- to generate AsciiDoc
2- to generate HTML

**Comment by mattadamson** [comment]
thanks Kabhal, this is similar to the example project swagger2markup-maven-project-template with a few changes

<config>
	<swagger2markup.pathsGroupedBy>TAGS</swagger2markup.pathsGroupedBy>
	<swagger2markup.markupLanguage>ASCIIDOC</swagger2markup.markupLanguage>
	<swagger2markup.separatedOperationsEnabled>true</swagger2markup.separatedOperationsEnabled>
	<swagger2markup.separatedDefinitionsEnabled>true</swagger2markup.separatedDefinitionsEnabled>
</config>

and

                        <configuration>
                            <backend>html5</backend>
                            <outputDirectory>${asciidoctor.html.output.directory}</outputDirectory>
                        </configuration>

**Comment by Kabhal** [comment]
You use separated documents, so you should :
- run Asciidoctor on all generated AsciiDoc files, not only on 4 generated adocs
- enable withInterDocumentCrossReferences, or you're links will be document-local only, and it won't work

**Comment by Kabhal** [comment]
In fact, when you use separated docs, you have 2 choices :
1- you create an AsciiDoc global doc and include ALL documents (and each definition and each operation), then generate 1 HTML, then local references will work
2- create several HTML files (1 for each .adoc), then you have to use withInterDocumentCrossReferences for links to work

**Comment by mattadamson** [comment]
thanks @Kabhal however I'm confused as if we specify separatedOperationsEnabled = true we see separate files created for each path. We can then reference then from the index.adoc and they are correctly embedded in the final HTML file.

We seem to be using a similar configuration to your option 1 however this doesn't appear to work.

**Comment by RobWin** [comment]
Might be a bug. Did you try @Kabhal suggestion and configured `swagger2markup.interDocumentCrossReferencesEnabled = true`?

**Comment by mattadamson** [comment]
I determined the reason here is because although a definition is included in the paths definition and the corresponding index entry added if the definition isn't explicitly listed too i.e. using 

include::{generated}/definitions/MyModel.adoc[]

This isn't an issue as it's perfectly reasonable to list the definition too as well as the reference from the related paths definitions e.g. as an input parameter or response. let's close this issue
