### ISSUE TITLE
Default values in model schema - swagger 1.3 spec

### ISSUE THREAD

**Issue by mattadamson** [Swagger2Markup/swagger2markup#133]
We're using swagger through camel 2.14 within the camel-swagger which isn't swagger 2.0 compliant. It does support swagger 1.3 as it's dependant on com.wordnik:swagger-annotations 1.3.7.

I can't seem to get the default value column within a model definition populated when I use swagger2markup on the URL end point. Does anyone know how to get defaults to appear in this version of swagger?

Thanks

**Comment by RobWin** [comment]
Could you please debug it?
We can't reproduce it without an example git repo.

**Comment by mattadamson** [comment]
sure I can try however where should I start from the source code?

**Comment by RobWin** [comment]
Which defaults do you mean? From path parameters or definition model properties?

**Comment by mattadamson** [comment]
From the definition model

**Comment by RobWin** [comment]
Have a look at https://github.com/Swagger2Markup/swagger2markup/blob/master/src/main/java/io/github/swagger2markup/internal/document/builder/MarkupDocumentBuilder.java#L209

**Comment by mattadamson** [comment]
thanks. I don't fully understand the code however it seems to rely on a StringProperty value being present from the underlying Model instance using getProperties keyed by the property name. I don't know how swagger / camel swagger sets this however I had added a default in this way

	@ApiModelProperty(notes = "getMyPropNotes", value = "getMyPropValue", required=true) @DefaultValue(value="getTenantMyPropDef")
	public String getMyProp()

Could it be related to the fact only defaults are available in mark up when using swagger 2.0?

**Comment by RobWin** [comment]
We use internally the (https://github.com/swagger-api/swagger-parser)[swagger-parser] to parse Swagger v1.2 and v2 into a Java Model. If the default values are missing, its because of the swagger-parser or the Camel integration.

**Comment by mattadamson** [comment]
thanks. I'm not sure what the underlying issue is however happy to close this as it's obviously not something we can resolve in swagger2markup
