### ISSUE TITLE
Linking to path operation file in a table after embedding

### ISSUE THREAD

**Issue by mattadamson** [Swagger2Markup/swagger2markup#134]
It's great to be able to generate separate operation adoc files and reference and embed them individually e.g.

include::{generated}/operations/postCreateDocument.adoc[]‏

However I'd also like to link to this embedded section within another part of the document e.g. a mapping table.  Consider 

.An example table
[width="40%",frame="topbot",options="header,footer"]
|======================
|Column 1 |Column 2
|1        |Item 1
|3        |
|6        |Three items
|======================

For the second row I'd like to embed a hyperlink to this included content. Obviously if I just reference again using the include syntax another copy is attempted to be embedded again at this point. 

Thanks

**Comment by RobWin** [comment]
Have a look at http://asciidoctor.org/docs/user-manual/#inter-document-cross-references

**Comment by mattadamson** [comment]
thanks Robert, this notation works well if you know the ID of operation section

<<id>> - Takes the title of the section 
<<id,new title> - Links to the section with an overridden title called "new title"

**Comment by RobWin** [comment]
You can see the generated IDs in the document itself, e.g. `postCreateDocument.adoc`

**Comment by mattadamson** [comment]
yes exactly. I was just following up for the benefit of others here

**Comment by RobWin** [comment]
Can I close the issue?

**Comment by mattadamson** [comment]
yes definitely
