### ISSUE TITLE
Example request / responses - including source tag

### ISSUE THREAD

**Issue by mattadamson** [Swagger2Markup/swagger2markup#135]
Only a minor enhancement however in each request / response adoc file I often put

[source,json]

which ascii doctor uses to recognise the request / response as JSON and format / highlight accordingly

It maybe nice to include this default value in the request / response examples when building to avoid having to include in each file

**Comment by RobWin** [comment]
Thats not possible, since the API could also provide many other Media types

**Comment by mattadamson** [comment]
Sorry I should have clarified I meant provide this default through a configurable value eg example.initialmarkup

**Comment by RobWin** [comment]
Won't implement
