### ISSUE TITLE
Swagger HTTP response table definition - customising

### ISSUE THREAD

**Issue by mattadamson** [Swagger2Markup/swagger2markup#137]
We're using camel 2.14 which as per https://github.com/Swagger2Markup/swagger2markup/issues/133 uses swagger 1.3. However I can't find a way when creating the Camel REST end points to express the swagger documentation for HTTP response codes e.g. where you'd use ApiResponse/s annotations on typcal code end points. 

I understand the camel integration issues for swagger is not related to this project however it maybe useful to provide an extension point for the response definitions.  The only thing I can find so far is 
OPERATION_RESPONSES_END for the paths extension. This is similar however it would mean creating an additional responses table for the new response code and string values we want to add below

**Comment by RobWin** [comment]
Hi,

I'm not sure if I understood the last sentence correctly.
Do you want to create a AsciiDoc file for each operation which contains a response table and inject it? Or something else?

You could also use a SwaggerModelExtension to add the Repsonses in Java code to the Swagger Model.

**Comment by mattadamson** [comment]
thanks Robert, very helpful.  I wanted to really try and build one single response table per operation i.e. perhaps have some generic error responses list that come from a common location e.g. in code but also keep the existing response codes if any are found by default from swagger. Having a separate generic table will work for many of our REST operations which fit within a certain "type" as we handle validation in a uniform manner.   We could also do this through the SwaggerModelExtension if we know the common paths although it would be nice to avoid hard coding any "known" paths that we want to map.  

It made me also consider if there are any hidden swagger annotations that we could apply, read within the model extension processing to determine specific business logic e.g. adding new response codes, but also ensuring the annotations don't get output into the documentation. e.g. consider a fictious annotation ApiGeneric(value="GenericValidator") that could be applied to an operation. Then the swagger 2 mark up extension might have access to this , determine it could apply certain additional swagger models or build specific mark up.  Perhaps this is the purpose of the swagger vendor extensions concept.

**Comment by RobWin** [comment]
Hi,

I think the easiest and fastest solution would be to add the Response headers feature to the camel-swagger-java module DSL. Maybe they except a Pull Request.
