### ISSUE TITLE
@ApiModelProperty.position not respected

### ISSUE THREAD

**Issue by marceloverdijk** [Swagger2Markup/swagger2markup#139]
I'm using `swagger2markup-gradle-plugin:1.0.0-SNAPSHOT` but the output does not respect the `@ApiModelProperty` `position` field.
Instead the fields in the resource are ordered alphabetically.

**Comment by RobWin** [comment]
Hi,

You mean the properties of a definition model are ordered alphabetically and not by position?

**Comment by marceloverdijk** [comment]
Yes indeed.

**Comment by RobWin** [comment]
You can configure the ordering of the properties. See `swagger2markup.propertyOrderBy` in http://swagger2markup.github.io/swagger2markup/1.0.0-SNAPSHOT/#_swagger2markup_properties

Default is `NATURAL`, but you can use `AS_IS`. Then we use the order of the input Swagger Spec.
It depends then on the framework which generates your Swagger Spec, if it supports the position field.

**Comment by marceloverdijk** [comment]
It seems Springfox does not order it correctly. Thx!
