### ISSUE TITLE
enum definitions show up empty in definitions.adoc

### ISSUE THREAD

**Issue by yzatslinear** [Swagger2Markup/swagger2markup#14]
I have an enum that is referenced in models that looks as follows:

```
       "mode": {
            "description": "mode",
            "enum": [
                false,
                true
            ],
            "type": "string"
        },
```
This entry shows up empty in definitions.adoc file

**Comment by RobWin** [comment]
Mh. I have a look at it today.

**Comment by RobWin** [comment]
? :-)

**Comment by yzats** [comment]
Appologies, somehow I didn't get notification with your original question. I'll be happy to email you my json file. To answer your question about boolean,  that was just a first example to came to me -- I don't really have that particular enum in my API definition.

**Comment by RobWin** [comment]
Thx. I'll have a look at it

**Comment by RobWin** [comment]
@yzats The following snippet is not rendered because of issue swagger-api/swagger-core#993. Unfortunately it is a problem in swagger-core itself.

```
"ACLReadInfo": {
            "properties": {
                "macAddress": {
                    "description": "MAC address of device",
                    "format": "macaddr",
                    "type": "string"
                }
            },
            "required": [
                "macAddress"
            ]
        }
```

The following snippet is not rendered and it seems to be an issue in swagger-core or swagger-parser as well:

```
"APState": {
            "description": "AP state",
            "enum": [
                "lost",
                "negotiating",
                "connected",
                "operational",
                "decommissioned"
            ],
            "type": "string"
        }
```

The Model is empty if you debug it:

![image](https://cloud.githubusercontent.com/assets/5815046/7343653/47b76068-ecc4-11e4-8cb3-f8a496d411c2.png)

I investigate it a little bit futher.

Kind regards,

Robert

**Comment by RobWin** [comment]
In swagger-parser class ModelDeserializer I can see APState.

![image](https://cloud.githubusercontent.com/assets/5815046/7343971/ea6d1502-ecc7-11e4-8249-49ad07ce0db1.png)

**Comment by RobWin** [comment]
The issue is that the Snippet is wrong. A model must always have properties. The properties attribut was missing in the snippet.
It must be

```
"APState": {
            "properties": {
                "enumValue": {
                    "description": "AP state",
                    "enum": [
                        "lost",
                        "negotiating",
                        "connected",
                        "operational",
                        "decommissioned"
                    ],
                    "type": "string"
                }
            }
        }
```

It is rendered then:

![image](https://cloud.githubusercontent.com/assets/5815046/7344482/0d73c8f8-eccc-11e4-8049-5f6324311832.png)

**Comment by yzatslinear** [comment]
Thanks for the clarification! I see you reopened the issue, can you clarify ?

**Comment by RobWin** [comment]
Just as a reminder for me that swagger-api/swagger-core#993 is still open.

**Comment by yzatslinear** [comment]
My interpretation of this discussion https://github.com/swagger-api/swagger-parser/issues/37 is that they're going to specifically add emailProperty but that's not really the gist of the issue. It should be possible to create any format.

**Comment by sunaina-ishi** [comment]
Hi , I am facing a similar issue but not with enum. My model definitions have discriminator and subtypes declaration but the it is not generating the code. My Model json look likes this.

models: {
    TimesheetEntryWireBase: {
   id: "TimesheetEntryWireBase",
   name: "TimesheetEntryWireBase",
   qualifiedType: "com.yt.nss.rest.domain.test.TimesheetEntryWireBase",
   properties: {
       type: {
            type: "string",
           qualifiedType: "java.lang.String",
            position: 0,
            required: true,
            allowableValues: {
                       values: [
                                       "STRING"
                                    ] ,
                        valueType: "LIST"
                        }
                 }
    },
   description: "Basic class for timesheet entry",
   baseModel: "java.lang.Void",
   discriminator: "type",
   subTypes: [
            "com.yt.nss.rest.domain.test.TimesheetProjectEntryWire",
            "com.yt.nss.rest.domain.test.TimesheetAdminEntryWire"
   ]
},
TimesheetProjectEntryWire: {
        id: "TimesheetProjectEntryWire",
        name: "TimesheetProjectEntryWire",
         qualifiedType: "com.yt.nss.rest.domain.test.TimesheetProjectEntryWire",
         properties: {
              type: {
                 type: "string",
                 qualifiedType: "java.lang.String",
                 position: 0,
                 required: true,
                 allowableValues: {
                       values: [
                                       "STRING"
                                    ] ,
                        valueType: "LIST"
                        }
             }
        }
}

Your help will be really appreciated.

**Comment by RobWin** [comment]
Hi,

could you please provide me a full Swagger.json example.

Kind regards,
Robert

**Comment by sunaina-ishi** [comment]
Below is my full JSON object. As you can see the model "TimesheetEntryWireBase" has subtypes and discriminator properties but the PDF format doesn't display these properties.

{
    apiVersion: "1",
    swaggerVersion: "1.2",
    basePath: "http://localhost:8082/query-rs",
    resourcePath: "/query-services",
    apis: [
        {
            path: "/query-services/timesheet",
            operations: [
                {
                    method: "GET",
                    summary: "testTimesheet",
                    responseClass: "void",
                    nickname: "testTimeSheet",
                    position: 0,
                    produces: [
                        "application/json"
                    ],
                    consumes: [
                        "application/json"
                    ],
                    parameters: [
                        {
                            name: "body",
                            required: false,
                            allowMultiple: false,
                            dataType: "TimesheetEntryWireBase",
                            paramType: "body"
                        }
                    ]
                }
            ]
        }
    ],
    models: {
        TimesheetEntryWireBase: {
            id: "TimesheetEntryWireBase",
            name: "TimesheetEntryWireBase",
            qualifiedType: "com.yt.nss.rest.domain.test.TimesheetEntryWireBase",
            properties: {
                type: {
                    type: "string",
                    qualifiedType: "java.lang.String",
                    position: 0,
                    required: true,
                    allowableValues: {
                        values: [
                            "STRING"
                        ],
                        valueType: "LIST"
                    }
                }
            },
            description: "Basic class for timesheet entry",
            baseModel: "java.lang.Void",
            discriminator: "type",
            subTypes: [
                "com.yt.nss.rest.domain.test.TimesheetProjectEntryWire",
                "com.yt.nss.rest.domain.test.TimesheetAdminEntryWire"
            ]
        },
        TimesheetProjectEntryWire: {
            id: "TimesheetProjectEntryWire",
            name: "TimesheetProjectEntryWire",
            qualifiedType: "com.yt.nss.rest.domain.test.TimesheetProjectEntryWire",
            properties: {
                type: {
                    type: "string",
                    qualifiedType: "java.lang.String",
                    position: 0,
                    required: true,
                    allowableValues: {
                        values: [
                            "STRING"
                        ],
                        valueType: "LIST"
                    }
                }
            }
        },
        TimesheetAdminEntryWire: {
            id: "TimesheetAdminEntryWire",
            name: "TimesheetAdminEntryWire",
            qualifiedType: "com.yt.nss.rest.domain.test.TimesheetAdminEntryWire",
            properties: {
                type: {
                    type: "string",
                    qualifiedType: "java.lang.String",
                    position: 0,
                    required: true,
                    allowableValues: {
                        values: [
                            "STRING"
                        ],
                        valueType: "LIST"
                    }
                }
            }
        }
    },
    position: 1
}

**Comment by RobWin** [comment]
Unfortunately all fields have missing double-quotes,

**Comment by RobWin** [comment]
What is not working. Which output do you expect?

**Comment by RobWin** [comment]
In Swagger Spec 1.2 property objects do not have a `required` field.

See https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#433-data-type-fields

**Comment by RobWin** [comment]
If my comments were helpful, please give me your GitHub star :D

**Comment by sunaina-ishi** [comment]
I will definitely give u a GitHub star. But could you please clarify few more doubts.
1.  "The subTypes property is not rendered, because it is Swagger Spec v1.2 specific.".
So by this do you mean that "swagger2markup" can't render subtypes for Swagger 1.2 but it renders for Swagger 2 ?
2.  "The field allowableValues is also not part of Swagger Spec v1.2". 
I am using "swagger2Spring-web" project and allowable values are appearing in the JSON.  So do you mean that it should not come in the output json.

3. When can we expect the "discriminator" property in the PDF ?.

Thanks,

**Comment by RobWin** [comment]
Did you tryvhttps://github.com/springfox/springfox? It supports Spring and generates Swagger Spec v2.0

**Comment by sunaina-ishi** [comment]
I did tried SpringFox. But SpringFox doesn't support polymorphism. And I needed that feature for my application.

**Comment by RobWin** [comment]
Please tell me what you would need and expect in a pdf. Which tables and columns?

**Comment by sunaina-ishi** [comment]
Ok. To be precise. The way JSON describes polymorphism/inheritance for "TimesheetEntryWireBase" object using subtypes. It would be good if we can have this relation in PDF as well. Did this make sense ?

**Comment by RobWin** [comment]
The swagger-parser parses the Swagger JSON into a [Swagger Pojo Model](https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-models/src/main/java/io/swagger/models). Swagger2Markup uses the parsed Swager Pojo Model. Unfortunately the [ModelImpl](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/ModelImpl.java) does have a `discriminator` field, but no information about its `subtypes`.

**Comment by sunaina-ishi** [comment]
Got that. Thanks a lot for your help.
