### ISSUE TITLE
Add example property of ApiModelProperty

### ISSUE THREAD

**Issue by mohlendo** [Swagger2Markup/swagger2markup#140]
Swagger2Markup version:
0.9.2
Problem description:
When describing an ApiModelProperty I sometimes provide an example value. How can I add that to the asciidoc markup?

**Comment by RobWin** [comment]
Please try the new v1.0.0-SNAPSHOT.
It supports examples and many more features.
http://swagger2markup.github.io/swagger2markup/1.0.0-SNAPSHOT

If you use Swagger2markup, we would love to get your GitHub Star.

**Comment by mohlendo** [comment]
Thanks! I had to create my own `Swagger2MarkupResultHandler` for my spring-boot app - but now it works! When will the 1.0.0 version be released?

**Comment by RobWin** [comment]
Hopefully next week.
