### ISSUE TITLE
Output definitions.adoc properties in well defined order

### ISSUE THREAD

**Issue by pkwarren** [Swagger2Markup/swagger2markup#141]
Swagger2Markup maven plugin version: 0.9.3
Swagger2Markup version: 0.9.2

Problem description:
As part of our build, we are running the swagger2markup-maven-plugin to generate asciidoc, which is then checked in to source control whenever domain objects change. I've noticed that the parameter output in the documentation is non-deterministic, so definitions.adoc changes content even though there are no changes made to the underlying model.

I believe this is the line of code which is iterating over the properties to determine how to output them: https://github.com/Swagger2Markup/swagger2markup/blob/v0.9.2/src/main/java/io/github/robwin/swagger2markup/builder/document/DefinitionsDocument.java#L200.

**Comment by Kabhal** [comment]
Hello,

This issue (#57) is resolved in Swagger2Markup master branch (1.0.0-SNAPSHOT).
You can now configure natural or custom ordering for :
- operations
- definitions
- parameters
- properties
- responses

**Comment by RobWin** [comment]
Check out the new documentation: http://swagger2markup.github.io/swagger2markup/1.0.0-SNAPSHOT/

**Comment by pkwarren** [comment]
Thanks @Kabhal and @RobWin - looking forward to the new release!

**Comment by RobWin** [comment]
If you like Swagger2markup, we would love to get your GitHub Star
