### ISSUE TITLE
Swagger 2 mark up extension to provide dynamic content from a database table / query

### ISSUE THREAD

**Issue by mattadamson** [Swagger2Markup/swagger2markup#142]
Some of our documentation content can actually be extracted from a database e.g. where we define structures which can be passed we define the expected values. This allows our customers to configure this information but also needs to be extracted for documentation.  If we extract it from the database it also allows us to avoid duplicating and defining directly in the documentation e.g. adoc files. 

We can of course create a custom swagger2markup extension e.g. Paths extension which has knowledge of specific operations and then determines queries to run, parse the results and bulid tables using the mark up builders classes. However rather than putting new queries / mapping in code it might be nice to create a generic extension which could use / recognise mark up specified in our adoc files, parse it and then build the resulting content dynamically e.g. consider 

{{SQL='SELECT firstCol, secondCol FROM MyModelDefnition'',Model=Contact',Cols='First column', ;'Second column'}}

where the firstCol and secondCol equal to some documentation attributes.  The extension would then run this query and map to the columns and build the mark up within the {{ and }} characters.

We could then reuse this in many other places of the document avoid adding new Java code every time with a switch statement e.g. if operation id == xx  run this code.

Is this possible with any of the extension points either directly in swagger2markup or in an ascii doctor specific extension perhaps?

Thanks

**Comment by RobWin** [comment]
Hi,

you could also use a Templating Engine like [Freemarker](http://freemarker.org/) to create your AsciiDoc files instead of writing an Asciidoctor extension or a Swagger2Markup extension.

**Comment by mattadamson** [comment]
Thanks Rob, I really want to add the template syntax in an ascii doctor file eg similar to the syntax I mentioned above. Is an ascii doctor extension even possible this way?

**Comment by RobWin** [comment]
I have never written an AsciiDoctor extension. But it should be possible. Sounds like a great idea. See https://github.com/asciidoctor/asciidoctorj#extension-api

**Comment by mattadamson** [comment]
@RobWin I've been exploring this through another ticket on the asciidoctorj issue forum

https://github.com/asciidoctor/asciidoctorj/issues/453

It sounded promising however as per my comment on their I'm not sure if that is the correct extension point. As I understand it seems the ascii doctor extensions work with the converted output e.g. you return HTML elements e.g. from the twitter examples.  

I actually want to modify the ascii doctor mark up and produce more ascii doctor mark up in specific places through the extension to return back. It doesn't seem like this is something swagger2markup should be doing but also I can't see ascii doctor does this. If I return ascii doctor markup it retains the ascii doc tags and doesn't get converted e.g. to PDF / HTML form

**Comment by mattadamson** [comment]
Hi @RobWin I've progressed this through https://github.com/asciidoctor/asciidoctorj/issues/453 and now have an ascii doctor block extension we can build a table from using the asciidoctor 1.6 snapshot for now. 

Related to this I found the MarkupDocBuilder type toString implementation didn't create the ascii doc syntax I expected or at least to work and show a table.  I copied the two relevant responses from that thread so we can follow up here now

> This runs like a train for me:
> 
>     @Override
>     public Object process(StructuralNode parent, Reader reader, Map<String, Object> attributes) {
>         Block block = createBlock(parent, "open", (String) null);
>         parseContent(block,
>             Arrays.asList(
>                 "|===",
>                 "|ID|Name",
>                 "",
>                 "|firstcol|secondcol",
>                 "|==="));
>         return block;
>     }
> 

Then my follow up 

> thanks that does indeed work perfectly. I was actually using what I thought was complete table mark up from the MarkUpDocBuilder instance shown below
> 
>         MarkupDocBuilder builder = new MarkdownBuilder();
>         final ArrayList<List<String>> rowColumns = new ArrayList<>();
>         final ArrayList<String> rowCells = new ArrayList<>();
>         rowCells.add("firstcol");
>         rowCells.add("secondcol");
>         rowColumns.add(rowCells);
>         List<MarkupTableColumn> columnSpecs = new ArrayList<MarkupTableColumn>();
>         columnSpecs.add(new MarkupTableColumn("ID"));
>         columnSpecs.add(new MarkupTableColumn("Name"));
>         builder.tableWithColumnSpecs(columnSpecs, rowColumns);
>         tableAsciiDocMarkup = builder.toString();
> This produced the same output without the leading |=== and trailing |=== however that's fine I can follow up on a different issue for the other project this class is part of.


Would you expect this to work e.g using tableWithColumnSpecs in this way? It certainly works fine when we use within a swagger2markup extension in this way

`					context.getMarkupDocBuilder().tableWithColumnSpecs(columnSpecs, rowColumns);
`
Thanks

**Comment by RobWin** [comment]
Comment deleted?

**Comment by mattadamson** [comment]
yes only as I realised a mistake / it wasn't relevant shortly after.  I've actually pasted the current code I have working in our extensions library now.  I'll try and move it into a separate project at some point

```
	@Override
	public Object process(StructuralNode parent, Reader reader, Map<String, Object> attributes)
	{
		Block block = createBlock(parent, "open", (String) null);
		
		ResultSet rs = null;
		Statement stmt = null;
		try
		{
			stmt = conn.createStatement();
			rs = stmt.executeQuery(attributes.get("sql").toString());

			ArrayList<List<String>> rowColumns = new ArrayList<List<String>>();
			while (rs.next())
			{
				final ArrayList<String> rowCells = new ArrayList<String>();
				for(int columnIndex = 0 ; columnIndex < rs.getMetaData().getColumnCount(); columnIndex++)
				{
					rowCells.add(rs.getString(columnIndex + 1));
				}
				rowColumns.add(rowCells);
			}

			List<MarkupTableColumn> columnSpecs = new ArrayList<MarkupTableColumn>();
			for(int columnIndex = 0 ; columnIndex < rs.getMetaData().getColumnCount(); columnIndex++)
			{
				columnSpecs.add(new MarkupTableColumn(rs.getMetaData().getColumnName(columnIndex + 1)));
			}

			MarkupDocBuilder builder = new AsciiDocBuilder();
			builder.tableWithColumnSpecs(columnSpecs, rowColumns);
			parseContent(block, Arrays.asList( builder.toString().split("\r\n")));
			return block;
		}
		catch (SQLException e)
		{
			throw new RuntimeException(e);
		}
		finally
		{
			DbUtils.closeQuietly(null, stmt, rs);
		}
	}
```

**Comment by RobWin** [comment]
Please create an instance of `MarkupDocBuilder` as follows:

`MarkupDocBuilder builder =  MarkupDocBuilders.documentBuilder(MarkupLanguage.ASCIIDOC)`
