### ISSUE TITLE
1.0.0-SNAPSHOT not working

### ISSUE THREAD

**Issue by mohlendo** [Swagger2Markup/swagger2markup#144]
I see, that you are about to release the 1.0.0 version - it seems that this somehow disturbs the latest 1.0.0-SNAPSHOT release, because there is a dependency to a version of markup-document-builder that is not compatible.

**Comment by RobWin** [comment]
Yes, I have some troubles with Bintray atm. I hope it is fixed tomorrow.

**Comment by RobWin** [comment]
You can use the 1.0.0 versions now. They are published on JCentral and Maven Central now.
Except the swagger2markup-extensions, but they should be available within this day. Bintray must approve my request to publish swagger2markup-extensions.

**Comment by mohlendo** [comment]
It works now, thanks!
