### ISSUE TITLE
APIs.guru: test on 200+ Swagger files for real-life APIs

### ISSUE THREAD

**Issue by IvanGoncharov** [Swagger2Markup/swagger2markup#146]
Maybe you would be interested in testing your lib against 200+ real-life Swagger files:
https://github.com/APIs-guru/api-models
They are validated and could be accessed through my [REST API](https://github.com/APIs-guru/api-models/blob/master/API.md)(no key needed).

**Comment by RobWin** [comment]
Hi, thx. I have a look at it.
