### ISSUE TITLE
validation constraints don't appear in generated docs

### ISSUE THREAD

**Issue by asafamit** [Swagger2Markup/swagger2markup#147]
Swagger2Markup version: 1.0.0

Problem description:

Validations in swagger json such as:
... "minLength":0,"maxLength":25}

are not appearing in the generated asciidoc and therefore HTML or PDF

**Comment by RobWin** [comment]
Yes, it's not supported yet, but it's on my todo-list.

**Comment by RobWin** [comment]
If you have some spare time, feel free to create a PR.

The plan is to add the missing fields to the description column of a model definition property: 

https://github.com/Swagger2Markup/swagger2markup/blob/master/src/main/java/io/github/swagger2markup/internal/document/builder/MarkupDocumentBuilder.java#L202-L220

**Comment by RobWin** [comment]
Be aware that the Swagger Model Interface `Property` does not have methods to get `minLength` or `maxLength`. Only the implementation class `StringProperty` does have these methods.
Which means you would have to add a method in our `PropertyUtils` which can extract the values, if the Property is an instance of  `StringProperty` and add the values to the description.

**Comment by asafamit** [comment]
Thanks, you got my star :)

**Comment by jfiala** [comment]
this should be fixed with this PR:
https://github.com/Swagger2Markup/swagger2markup/pull/156
