### ISSUE TITLE
Inheriting definitions does not work sorting properties AS_IS

### ISSUE THREAD

**Issue by marceloverdijk** [Swagger2Markup/swagger2markup#152]
Swagger2Markup version: 1.0.0

Problem description:

Inheriting definitions and using `<swagger2markup.propertyOrderBy>AS_IS</swagger2markup.propertyOrderBy>` does not seem to work.

The super definition's fields are sorted `AS_IS` correctly, but the sub definition's fields are not sorted at all. Also not alphabetically; random it seems.

A full example + description can be found here:
https://github.com/marceloverdijk/swagger2markup-composition-sorting-issue

/cc @Kabhal

**Comment by starlightknight** [comment]
I had noticed this recently as well in one of my tests. This fix will be good to have :-)

**Comment by marceloverdijk** [comment]
Fixed in 

```
<dependency>
    <groupId>io.github.swagger2markup</groupId>
    <artifactId>swagger2markup</artifactId>
    <version>1.0.1-SNAPSHOT</version>
</dependency>
```
