### ISSUE TITLE
Slate markdown

### ISSUE THREAD

**Issue by neoecos** [Swagger2Markup/swagger2markup#16]
The generated markdown look ugly in slate.

Would be beautiful a new markup type, that is SLATE and is a markdown for slate =D

**Comment by gbaird** [comment]
:+1: , wish I knew better how to help!

**Comment by RobWin** [comment]
I wont have time to implement this. PR are welcome.

**Comment by RobWin** [comment]
Please have a look at https://github.com/RobWin/asciidocular

**Comment by Relequestual** [comment]
@RobWin if RPs are welcome, then surely you wouldn't want to close the issue, so people can find it to make PRs?

**Comment by RobWin** [comment]
Sure. I can reopen it. 
I thought I close it, because no one commented something or actually contribured something to this topic.

**Comment by Relequestual** [comment]
Personally, I only close issues if I consider them to be resolved or no longer relevant.
