### ISSUE TITLE
Add test cases for validation constraints

### ISSUE THREAD

**Issue by jfiala** [Swagger2Markup/swagger2markup#160]
Validation constraints:
* [x] minLength
* [x] maxLength
* [x] pattern
* [x] minimum
>>> part of last version of Swagger-Petstore-API definition & should be used there after updating
>>> added example for minimum to order.category
* [x] maximum
>>> part of last version of Swagger-Petstore-API definition & should be used there after updating
>>> added example for maximum to order.category

I added the following example to 

swagger_petstore.yaml, Category.name
* minLength: 0
* maxLength: 255
* pattern: "[A-Za-zäöüÄÖÜß]{0,255}"

swagger_petstore.yaml, Order.quanity:
* minimum: 0.0
* maximum: 10000.0

Please advise where additional samples should be added?
The currently used swagger_petstore.yaml doesn't contain any validation constraints (minLength/maxLength/pattern/min/max).

The current version of the swagger petstore definition (see #159) would contain an example for min/max, which could be used after upgrading to it.

**Comment by jfiala** [comment]
This should be fixed for the new validation constraints with https://github.com/Swagger2Markup/swagger2markup/pull/156 (however, I had to edit the Swagger-Petstore-API-file manually, as there are no existing samples in the currently used old version).

**Comment by Kabhal** [comment]
- You can provide a new swagger in YAML (src/test/resources/yaml) or JSON (src/test/resources/json).
- Then create a new test for constraints in src/test/java/io/github/swagger2markup/AsciidocConverterTest.java by inspiring on other ones.
- You can copy generated results in build/test/asciidoc/{name you chose} to src/test/resources/expected/{name you chose}

**Comment by jfiala** [comment]
OK, so is it better to use the Swagger Petstore for testing (in this case it will allow only for testing min/max as the others are missing there) or should I use a small snippet (e.g. model Cat) for providing the tests? 
IMHO it appears better to use an isolated example, as it is easier for debugging (as e.g. swagger_enums.json, so I'd simply add swagger_validation.json).

**Comment by Kabhal** [comment]
ok for isolated example.

**Comment by jfiala** [comment]
added isolated example in directory validators.
