### ISSUE TITLE
Support for asciidoc content in tables (for definition properties)

### ISSUE THREAD

**Issue by orcun** [Swagger2Markup/swagger2markup#162]
I am using GFM in property descriptions. Some of the syntax is working, i.e. italics, bold, monospace. However some isn't working, i.e. headers, lists.
I don't have much experience with asciidoc but looking at [quick reference](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/): _Table with column containing AsciiDoc content_, there is an extra `a` beside the column width. I am guessing this is missing from the generated adoc files for description columns.

I hope this information is enough but if not please let me know and I will try my best.

**Comment by Kabhal** [comment]
You can add the ```a``` flag in ```withMarkupSpecifiers(AsciiDoc, ...)``` parameter (for the Description column only) in the various tables that need it.
Please note that your documentation, if it contains advanced Markup for properties descriptions, will then render correctly only using AsciiDoc output. Markdown and Confluence Wiki rendering of tables containing advanced formatting is not supported by these languages. Moreover long properties descriptions don't always fit well in tables, so an advice is you keep your properties descriptions short enough when possible.

**Comment by RobWin** [comment]
Can I close the issue?

**Comment by orcun** [comment]
I was using the cli and had to edit the generated adoc file. So such a change would still be useful if there is no harm.

**Comment by RobWin** [comment]
Ok. You are right. The AsciiDoc cell specifier is missing.

Btw, if you use and like Swagger2markup, we would love to get your GitHub Star.

**Comment by kegstyle** [comment]
I'm also waiting this enhancement.
When is applied?

**Comment by RobWin** [comment]
I won't have time to implement this.
Please provide a PR, if you need this feature urgently.

**Comment by atomfrede** [comment]
@RobWin Would like to fix this low hanging fruit during hacktoberfest. I would add the `a` specifier in the `TableComponent` such that every table may contain `.adoc` content. Is that okay for you?

**Comment by RobWin** [comment]
Yes sure. That would be awesome. I guess this must be fixed in the markup-document-builder
