### ISSUE TITLE
Snapshop documentation linked incorrectly?

### ISSUE THREAD

**Issue by mattadamson** [Swagger2Markup/swagger2markup#163]
I noticed this was linked from the main page https://github.com/Swagger2Markup/swagger2markup

http://swagger2markup.github.io/swagger2markup/1.0.1-SNAPSHOT/

in the reference documentation. Is that the intention?

**Comment by RobWin** [comment]
No. I have to fix the github-pages upload. Thx.
But the documentation is still valid.
