### ISSUE TITLE
Unable to pass Empty Values in queryParam

### ISSUE THREAD

**Issue by rathishkumar89** [Swagger2Markup/swagger2markup#165]
Hi Rob,
  Due to the migration of swagger installation method from npm to bower there is an issue we are facing in swagger.When we were using the previous method,we were able to modify the js to accept the empty queryParam. But now with the bower install route swagger gets downloaded on the air, due to this we were not able to edit the swagger script , swagger adds queryParam={queryParam} for empty queryParam.

Swagger is providing allowEmptyValue attribute for Optional fields when the "paramType"  is "query". This attribute allows us to pass empty-valued parameters but  there is no impact on the request it still holds the queryParam={queryParam}.Eventhough the allow-EmptyValue is set as true. We tried with the above feature,  unfortunately it is not functional.

Is there any workaround? Or is there any other possible way to achieve this?.

**Comment by RobWin** [comment]
Hi, can you show an example please. I'm not sure, if I understand your issue.

**Comment by rathishkumar89** [comment]
**Web-Request**
{
		"path": "/pets/getPet.do",
		"operations": [{
			"method": "GET",
			"summary": "This API endpoint retrieves entire pets.",
			"notes": "Returns the paginated list.",
			"type": "void",
			"nickname": "getPet.do",
			"parameters": [{
					"name": "petType",
					"description": "Possible types",
					"required": false,					
					"format": "string",
					"in": "query"
				},

				 {
					"name": "test",
					"description": "The value test.",
					"required": true,
					"format": "String",
					"in": "query"					
				}
			]
}]


**Output for above request:**

/pets/getPet.do?test=dog
 
**Expected output:**

/pets/getPet.do?petType=&test=dog
 
So we introduced, **allowEmptyValue : true** for parameter "petType" to get expected output. But it is not functional. Can you please let us know the alternative to achieve the expected output.

**Comment by rathishkumar89** [comment]
Hi Rob,

The word not functional denotes that we are unable to construct URL (expected one). So, what is the proper usage of attributes to get the expected URL from the above example.

**Comment by RobWin** [comment]
Can you show me the generated Asciidoc/Markdown output which is not correct?

Is the URL generated by Swagger2Markup as an example?

**Comment by rathishkumar89** [comment]
1) we are not converting to Asciidoc. Using swagger we are calling the webservice.
2) yes swagger generates the URL based on the Input json

**Comment by RobWin** [comment]
I think you have opened an issue in the wrong project.

**Comment by RobWin** [comment]
See https://github.com/swagger-api for Swagger related projects.
