### ISSUE TITLE
swagger2markup-import-files-ext not working with security-section

### ISSUE THREAD

**Issue by afdia** [Swagger2Markup/swagger2markup#166]
Testcase:
check out https://github.com/Swagger2Markup/swagger2markup-maven-project-template and add "include::{generated}/security.adoc[]" to the index.adoc (I guess it's not intentional but the security section is missing in the original template even though the begin and end hook files do exist)

Expected:
security/document-begin-text.adoc and security/document-end-text.adoc should be added around the generated security.adoc file

Instead:
The files are ignored

It seems to be a general problem with either the extension mechanism or the swagger2markup-import-files-ext module, but the hooks for the security section are not used.

**Comment by RobWin** [comment]
Thx. I have a look at it.

**Comment by RobWin** [comment]
Mh very strange. The gradle-project-template works, but the maven template not. I can't find any differences. All other hooks in the maven template work as expected.
The extension library which is used is the same in both projects which means that it can't be a general issue.
