### ISSUE TITLE
1.0.1 anytime soon ?

### ISSUE THREAD

**Issue by JanC** [Swagger2Markup/swagger2markup#169]
Hi,
I'm using [swagger2confluence](https://gitlab.slkdev.net/starlightknight/swagger-confluence) that itself uses swagger2markup `1.0.0` but there is an issue that seems to be fixed in `1.0.0`

[See my reported issue](https://gitlab.slkdev.net/starlightknight/swagger-confluence/issues/10) 

Is the `1.0.1` going to be released officially?

cheers,
Jan

**Comment by RobWin** [comment]
Hi, please enter a GitHub Star :)
I'm on parental leave. I hope I can release it soon.

**Comment by JanC** [comment]
Congrats! Ok, I'm looking forward to it.

**Comment by yeskov** [comment]
+1 for 1.0.1 release request.
For now we are forced to use 1.0.1-SNAPSHOT due to bug in 1.0.0

**Comment by RobWin** [comment]
Is the SNAPSHOT version stable? Or anything not working for you?

**Comment by JanC** [comment]
In my case it's been working fine

**Comment by RobWin** [comment]
Done. V1.0.1 has been released.

**Comment by JanC** [comment]
whoop whoop, thanks 👍

**Comment by RobWin** [comment]
Your are welcome

**Comment by yeskov** [comment]
Thank you! In my case 1.0.1-SNAPSHOT was working fine too.
