### ISSUE TITLE
Swagger spec file as a command-line input?

### ISSUE THREAD

**Issue by who** [Swagger2Markup/swagger2markup#17]
Is there a way to execute swagger2markup via jar, passing in a file path or URL to a swagger spec, and have it output markdown/etc ?

I'm looking for something like swagger-codegen, but for docs.

**Comment by RobWin** [comment]
No, not yet. But a Java Main class which invokes swagger2markup is a 5-liner I guess.
If you use Gradle, you can use https://github.com/RobWin/swagger2markup-gradle-plugin to create the docs during the build phase.

**Comment by mxl** [comment]
@who I made CLI https://github.com/mxl/swagger2markup-cli. Please checkout.

**Comment by RobWin** [comment]
@mxl Very nice. Thx. Do you mind if I reference it in my documentation?

**Comment by mxl** [comment]
@RobWin Yes, of course.

**Comment by RobWin** [comment]
http://swagger2markup.readme.io/docs/cli

If you like Swagger2markup, I would love to get your GitHub star.
