### ISSUE TITLE
StackOverflow when examples have cyclic references

### ISSUE THREAD

**Issue by RobWin** [Swagger2Markup/swagger2markup#173]
Hi. I had troubles generating documentation with examples when a resource included itself. The code for the example creation does not stop when cyclic references are used. Now there is a constant in ExampleUtil that restricts the depth of the example to a certain level so that the recursion is visible but stops at a certain level (only "..." is displayed in the example when the max depth is reached).

Regards @mhswisscom

**Comment by rchargel** [comment]
I am currently using version 1.0.1 and I'm definitely getting StackOverflowErrors with a model that references itself.

DeviceModel has components, which are of type DeviceModel.

When are you thinking this will be fixed?

**Comment by RobWin** [comment]
Hi,
can you try 1.0.2-SNAPSHOT?

**Comment by RobWin** [comment]
Btw if you use swagger2markup, we would love to get your GitHub star

**Comment by rchargel** [comment]
Yes, 1.0.2-SNAPSHOT appears to be working for me. When are you planning on cutting the next release?

**Comment by RobWin** [comment]
The example generation is still incubating and is not working properly.
I'm generating real-life HTTP request/response examples by testing my API and including them into the documentation via a Swagger2markup extensions.
I use Spring Rest Docs to generate the example snippets.

**Comment by austek** [comment]
I'd say, actual issue was fixed and this one should be closed. if examples are still a problem raise another issue please

**Comment by vishalbinodruplal** [comment]
Hi @RobWin,

Thanks in Advance for all you help and support.

I'm facing the same issue which is mentioned in this issue. So could you please help us in knowing that in which version of Swagger2markup plugin this issue is fixed and resolved, as I cannot se the version 1.0.2-snapshot present on the public maven repository.

Thank and Regards,
Vishal Kumar Yadav

**Comment by austek** [comment]
Current snapshot version is `2.0.0-SNAPSHOT` available on https://oss.jfrog.org/artifactory/oss-snapshot-local/

https://oss.jfrog.org/artifactory/oss-snapshot-local/io/github/swagger2markup/

openapi v3 is supported as well by openapi2markup

**Comment by vishalbinodruplal** [comment]
Hi @austek ,

I have tried you version of swagger2markup but still I'm facing the stackoverflow error for cyclic dependencies in swagger yaml file.

It seems like this issue is not fixed in this version.

Thanks and Regards,
Vishal Kumar Yadav
