### ISSUE TITLE
Support for readOnly property in the generated documentation.

### ISSUE THREAD

**Issue by rajeshkamal** [Swagger2Markup/swagger2markup#176]
@RobWin Currently the generated HTML/PDF documentation only contains values of **_"required"_** field. It will also be good if we can get the support for the **_"readOnly"_** value of a property as well.

The swagger spec seems to contains provisions for **_"required"_** and **_"readOnly"_** for the models/definitions.

And it also part of the generated Swagger Spec from Springfox.

```
"Foo": {
      "type": "object",
      "required": [
        "name",
      ],
      "properties": {
        "id": {
          "type": "string",
          "description": "Foo unique identifier",
          "readOnly": true
        },
        "name": {
          "type": "string",
          "description": "Foo name"
        }
      },
      "description": "Foo model"
    }
```

Swagger2Markup version: 0.9.2

**Comment by RobWin** [comment]
Hi, thx. I have a look at it.
Do you really still use v0.9.2?
You should update to 1.0.1 :smile:

**Comment by rajeshkamal** [comment]
Thanks @RobWin. Will directly upgrade to v1.0.2 once you have support for _**"readOnly"**_  😉

**Comment by RobWin** [comment]
Ups. I forgot its already implemented in v1.0.1

**Comment by rajeshkamal** [comment]
Wowww.. Let me try now and update here.... 😃

**Comment by rajeshkamal** [comment]
springfox-staticdocs - 2.5.0 has dependency only with swagger2markup - 0.9.2

I could not find swagger2markup 1.0.1 in maven repo? 😞

**Comment by RobWin** [comment]
Yes, you don't really need springfox-staticdocs anymore. Have a look at the demo: https://github.com/Swagger2Markup/spring-swagger2markup-demo

And have a look at the documentation: http://swagger2markup.github.io/swagger2markup/1.0.1/

The maven group id has been changed fromfrom `io.github.robwin` to `io.github.swagger2markup`.

**Comment by rajeshkamal** [comment]
Thanks @RobWin, I moved to the latest v1.0.1 and it is working. I can see the support for **_readOnly_** property along with **_required/optional_**

**Comment by RobWin** [comment]
Very nice 👍
