### ISSUE TITLE
generatedExamplesEnabled issues

### ISSUE THREAD

**Issue by mwickens** [Swagger2Markup/swagger2markup#180]
Swagger2Markup CLI version 1.0.1

A couple of issues with generated examples. 
- Request path examples have `json :` prepended.

```
json :
"/categories"
```
- My response examples are always just:

```
json :
"object"
```
- Properties of model objects referencing other models are getting this kind of thing generated for examples. Looks like literal markdown.

| Name | Description | Schema |
| --- | --- | --- |
| **start**  <br>_optional_ | **Example** : `"[hourspec](#hourspec)"` | [HourSpec](#hourspec) |
| **end**  <br>_optional_ | **Example** : `"[hourspec](#hourspec)"` | [HourSpec](#hourspec) |

[generatedExamplesEnabledIssue.zip](https://github.com/Swagger2Markup/swagger2markup/files/437856/generatedExamplesEnabledIssue.zip)

**Comment by RobWin** [comment]
Hello,

the `generateExamples` feature is unfortunately still incubating and not well-tested and "production-ready" .
I personally don't use the feature, but either 
1. create examples with meaningful data by hand 
2. generate the examples by testing my API (e.g. with Spring Rest Docs) and include them into the documentation by using the swagger2markup-spring-restdocs or swagger2markup-import-files extension.

**Comment by mwickens** [comment]
Thanks, will do. Loving Swagger2Markup otherwise.

**Comment by RobWin** [comment]
Thx. Nice to hear. I reopen the issue so that we (or someone else) can fix it someday.

**Comment by mciosmak** [comment]
I found similar problem (swagger2markup 1.2.0) with generating examples.

For array in response:

> "200":
>   description: OK
>   schema:
>   type: array
>   items:
>     $ref: "#/definitions/MyExampleObject"`

Generates string "array" instead of json:

> ![obraz](https://cloud.githubusercontent.com/assets/9325632/21901681/fb646576-d8f8-11e6-99a8-2c493ffcbd51.png)

**Comment by cascer1** [comment]
Hi,

This seems to be the case for all responses with type `array` - the `$ref`erenced schema isn't parsed. I was able to isolate the issue and it should be fixable [here](https://github.com/Swagger2Markup/swagger2markup/blob/2f33522e6dbade76d0623345837cdff87eb92431/src/main/java/io/github/swagger2markup/internal/component/PathOperationComponent.java#L377). However, I was not able to resolve the issue at the time.

**Comment by RobWin** [comment]
@cascer1 Would you like to handle this issue?

**Comment by cascer1** [comment]
@RobWin Sure, I was already planning on fixing the example generation soon.

**Comment by cascer1** [comment]
I've made quite a lot of progress already. 

For example, this is now the example for response 200 of `GET /pets/findByStatus` in the `testWithGeneratedExamples` test.

![example](https://ducohosting.com/screenshots/isaac9b5e90a1127f66af1eedb698e19f6c77.png)

Just need to modify a few unit tests to expect this improved result and it'll be good to go!

**Comment by explode** [comment]
Could you please look at formData POST params too?
[testjson.txt](https://github.com/Swagger2Markup/swagger2markup/files/1103209/testjson.txt)
The provided case contains two required string form params, two optional string params and one optional boolean param.
The expected request formData output is `reqStr1=string&reqStr2=string` but generated example contains only `true`.
Also it would be good to handle enums like Swagger does. It selects the first enum item as example field's value instead of just `string`.
