### ISSUE TITLE
how to add chinese language support?

### ISSUE THREAD

**Issue by mingkaili** [Swagger2Markup/swagger2markup#182]
Thanks for raising a Swagger2Markup issue. Please provide a brief description of your problem along with the Swagger2Markup version you are using. If possible, please also consider putting together a complete Swagger specification that reproduces the issue. It's better if the Swagger specification is small and isolate the issue.

Swagger2Markup version:1.0.0

Problem description:
how to add chinese language support?
Swagger2Markup version 1.0.1 need jdk8, but we only use jdk7. So we only choose Swagger2Markup version 1.0.0 . The io.github.swagger2markup.Language of Swagger2Markup version 1.0.0 doesn`t support Chinese language. I want to add Chinese language, but I don`t know how to do it. Please help me!!!!! My english is not very well.

thanks very much!

**Comment by mingkaili** [comment]
<groupId>io.github.swagger2markup</groupId>
<artifactId>swagger2markup</artifactId>
<version>1.0.0</version>

**Comment by mingkaili** [comment]
【Language.valueOf("")】How to use this method ? I don`t know how to use it to add other language.

**Comment by RobWin** [comment]
Hi, if you like and use swagger2markup, we would love to get your GitHub Star.

You just have to add/provide a Chinese translation of the language property file.

**Comment by mingkaili** [comment]
@RobWin hello, RobWin! Thank you very much for your help! I don`t know what is my GitHub Star, but I think you want to let me join in the community of developing swagger2markup. I am very happy to join in it. Now what should I do for join in it? How do I submit the language property file(https://github.com/Swagger2Markup/swagger2markup/blob/master/src/main/resources/io/github/swagger2markup/lang/labels_en.properties) ? Thank you very much !!!

**Comment by RobWin** [comment]
About GitHub Stars: https://help.github.com/articles/about-stars/

About Pull Requests. Please read this, if you want to contribute the chinese properties file: https://help.github.com/categories/collaborating-on-projects-using-issues-and-pull-requests/

**Comment by mingkaili** [comment]
@RobWin Ok! Thank you!! Let me have a look !

**Comment by RobWin** [comment]
Works for you?

**Comment by mingkaili** [comment]
@RobWin Hello! I am very busy recently! So I have no time to test it. Thank you for your inquiry!!!
I shall test it as soon , please wait for my information some days!!!
