### ISSUE TITLE
Table columns too narrow

### ISSUE THREAD

**Issue by cascer1** [Swagger2Markup/swagger2markup#183]
Swagger2Markup version: 1.0.1

Problem description:

When the plugin generates a table (for example to list parameters for endpoints or security definitions) the columns are too narrow, causing text to be cut off to the next line.

![example](https://cloud.githubusercontent.com/assets/7243299/18198176/72dbda96-70fb-11e6-8e76-32b3cf936e53.png)

Please see the included sample swagger spec:

[spec.zip](https://github.com/Swagger2Markup/swagger2markup/files/451575/spec.zip)

[example.pdf](https://github.com/Swagger2Markup/swagger2markup/files/451566/example.pdf)

As you can see, the right column could be shrinked down to allow the first column to contain all text.

**Comment by Kabhal** [comment]
Hi,
Here some discussion about this problem : https://github.com/Swagger2Markup/swagger2markup/pull/149

**Comment by cascer1** [comment]
Thanks! Looks like I hadn't searched as well as I thought.

**Comment by RobWin** [comment]
Can I close this issue?

**Comment by cascer1** [comment]
Oh my apologies. Yeah, it seems this issue is a duplicate of #149.

**Comment by RobWin** [comment]
Thx

**Comment by RobWin** [comment]
Thx.
Btw if you use and like Swagger2Markup, we would love to get your GitHub star.
