### ISSUE TITLE
Markup with several paths

### ISSUE THREAD

**Issue by atdiff** [Swagger2Markup/swagger2markup#184]
Swagger2Markup version: 1.0.1
Just an idea.  When a Swagger file has many paths and examples, the documentation can appear somewhat bogged down and hard to navigate with all of the scrolling that might be necessary through the list of paths.  It might be a good idea to provide a list of links to the API paths (anchored in the page), so that there's a simple avenue to get to that data. My $0.02 worth...

**Comment by RobWin** [comment]
Hi, which Markup do you generate? Markdown, AsciiDoc? Do you mean some sort of Table of Contents (ToC)?

**Comment by atdiff** [comment]
I'm generating CONFLUENCE_MARKUP.  A ToC of sorts would be good or something along those lines - primarily for the paths is what I'm thinking.

**Comment by RobWin** [comment]
There are libraries for Markdown and AsciiDoc which generate a HTML documentation and also a ToC . For example, Asciidoctor generates a ToC for you.

If you stick with Confluence Wiki, you can create a Swagger2Markup extension which generates a ToC for your paths. See Extension SPI: http://swagger2markup.github.io/swagger2markup/1.0.1/#_extension_spi

You have to create a `PathsDocumentExtension` and use the extension point `DOCUMENT_BEGIN` to generate a ToC after the `Paths` chapter header.
