### ISSUE TITLE
Possible to change markup styling?

### ISSUE THREAD

**Issue by atdiff** [Swagger2Markup/swagger2markup#185]
Swagger2Markup version: 1.0.1
For a project I'm working on, I'd like to rearrange the look and feel of the rendered markup.  There are several Swagger files that we're using and wiki pages that we're creating.  So is there a way to either use a template of some sort or a CSS file type thing to structure the UI differently?  Or is there a way to have a custom Confluence wiki markup generator that provides flexibility in how the markup is generated and styled?

**Comment by RobWin** [comment]
What do you mean by look and feel? Colors or structure? There is currently no way to restructure the output via templates.
What would you like to change?

**Comment by atdiff** [comment]
Yes. :)  A little bit of all of the above or at least to have the flexibility to do so.   One developer I showed the documentation to said "I think the page could  be laid out better to make it more human readable, but that’s just my humble opinion".  I'm sure with it being markup there will be some limitations, so maybe we need to go the route of using HTML or something in that direction.  Just curious what's possible.
In a quick google search, I saw some references to styling like slate or other similar options. But wasn't sure how that fits in with swagger2markup.  We're currently housing our documentation in a Confluence wiki, so that will have some limitations as well.

**Comment by RobWin** [comment]
Swagger2Markup does not generate HTML for you. You can use any library to convert Markdown/AsciiDoc into HTML and use your own custom CSS file.

Do you have to use a Confluence wiki for your API documentation? If that's the case, Slate is also no option for you.
