### ISSUE TITLE
Use Docker to build this project and convert docs inside container!

### ISSUE THREAD

**Issue by zyfdegh** [Swagger2Markup/swagger2markup#188]
Thanks for raising a Swagger2Markup issue. Please provide a brief description of your problem along with the Swagger2Markup version you are using. If possible, please also consider putting together a complete Swagger specification that reproduces the issue. It's better if the Swagger specification is small and isolate the issue.

Swagger2Markup version: master commit c5cfe10fa6bf4af46920e03f31dad90c4295ce5a

Problem description:

 I think it will be better to build this project inside docker container. In that way, I no longer need to install jdk, gradle on my machine. So is there any idea on add a Dockerfile in this repo?

**Comment by RobWin** [comment]
Hi,

thx for your GitHub Star.
I created a Swagger2Markup image 2 days ago and published it on DockerHub.
See: https://github.com/Swagger2Markup/swagger2markup-cli/blob/master/Dockerfile
The Dockerfile can be improved and I would be happy to get help.

Just run `docker pull swagger2markup/swagger2markup`.
You can mount a directory to provide your config file.

**Comment by zyfdegh** [comment]
Wow, good job.
I searched on DockerHub and found your repo before, but gave up due to no description and usage docs. 

You can simply delete that repo, and create a new **Automated Build** one. ;-)

**Comment by RobWin** [comment]
Its an automated build via Docker Cloud. But I guess the readme is missing, because the projects use AsciiDoc instead of Markdown for documentation.
