### ISSUE TITLE
guava 18.0 causes dependecy hell

### ISSUE THREAD

**Issue by avishaybennatan** [Swagger2Markup/swagger2markup#189]
dear swagger2markup team,
could you please update the guava dependency for the project ? this old version of guava causes a lot of issues with other maven project using the latest guava version (19.0),
 Thanks.

**Comment by RobWin** [comment]
Hi,

unfortunately it's a transitive dependency of the swagger-parser library which is not under our control.

If you use and like swagger2markup, we would love to get your GitHub star.
