### ISSUE TITLE
ZH-language is not  display correctly!

### ISSUE THREAD

**Issue by liangjw** [Swagger2Markup/swagger2markup#197]
Swagger2Markup version:
1.1.0
Problem description:
I found Swagger2Markup  loading language properties by ResourceBundle. But ResourceBundle uses 'IOS' charset by default and language_zh.properties uses 'UTF-8' . 
The reason above causes meta data filling by  messy code.
are there any solutions for solving that problem instead of updating source code?

**Comment by RobWin** [comment]
Hi,

thanks for raising the issue.
We can only fix the resource file. Could you please create a PR a provide a correct resource file?

**Comment by Kabhal** [comment]
Yes, and the *native2ascii* tool can be used to automatically do that ..

**Comment by Kabhal** [comment]
Anyway, even if writing properties in ISO is robust, it's a pain to maintain, particulary for languages needing 100% unicode codes.
An alternative could be support UTF-8 in properties by providing a small abstraction over ResourceBundle which systematically convert string as suggested in http://stackoverflow.com/questions/4659929/how-to-use-utf-8-in-resource-properties-with-resourcebundle

**Comment by RobWin** [comment]
Nice, I didn't know native2asciidoc. Thx!

**Comment by liangjw** [comment]
Nice !! it works.

**Comment by RobWin** [comment]
This is fixed in the upcoming Version 1.1.1
You can already try `1.1.1-SNAPSHOT`

**Comment by RobWin** [comment]
Fixed in v1.1.0
