### ISSUE TITLE
Group By Tags / Table of Contents

### ISSUE THREAD

**Issue by starlightknight** [Swagger2Markup/swagger2markup#203]
Swagger2Markup version:
1.1.0

Problem description:

Hi there,
I'm generating asciidoc while grouping by tags:

```
Swagger2MarkupConfig config = new Swagger2MarkupConfigBuilder()
                    .withMarkupLanguage(MarkupLanguage.ASCIIDOC)
                    .withOutputLanguage(Language.EN)
                    .withPathsGroupedBy(GroupBy.TAGS))
                    .withOperationOrdering(OrderBy.AS_IS)
                    .build();
```

When I do this, I get, for example:

Table of Contents

- Overview
  - ...
- Resources
  - Pet
  - Store
  - User

Where the links in resources are individual tags. 

Is it possible to get the table of contents to drill down one level further to individual operations like so?

- Overview
  - ...
- Resources
  - Pet
    - Update an existing pet
    - ....
  - Store
  - User

This would be helpful for quickly jumping to specific points in the documentation when a tag has a handful of operations associated with it, but still retaining the benefit of grouping / organizing them by tag..

**Comment by RobWin** [comment]
Hi,
how do you generate the AsciiDoc HTML documentation? Using an Asciidoctor plugin or directly via code?

It's easy: You just have to set the Asciidctor attribute `toclevels` to '3'. See http://asciidoctor.org/docs/user-manual/#levels
