### ISSUE TITLE
Error creating extended parser class

### ISSUE THREAD

**Issue by raderio** [Swagger2Markup/swagger2markup#204]
> Exception in thread "main" java.lang.RuntimeException: Error creating extended parser class: null
>         at org.parboiled.Parboiled.createParser(Parboiled.java:58)
>         at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:92)
>         at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:61)
>         at nl.jworks.markdown_to_asciidoc.Converter.convertMarkdownToAsciiDoc(Converter.java:42)
>         at io.github.swagger2markup.markup.builder.internal.AbstractMarkupDocBuilder.convert(AbstractMarkupDocBuilder.java:399)
>         at io.github.swagger2markup.markup.builder.internal.AbstractMarkupDocBuilder.importMarkupStyle1(AbstractMarkupDocBuilder.java:436)
>         at io.github.swagger2markup.markup.builder.internal.asciidoc.AsciiDocBuilder.importMarkup(AsciiDocBuilder.java:251)
>         at io.github.swagger2markup.markup.builder.internal.AbstractMarkupDocBuilder.importMarkup(AbstractMarkupDocBuilder.java:391)
>         at io.github.swagger2markup.internal.document.builder.MarkupDocumentBuilder.swaggerMarkupDescription(MarkupDocumentBuilder.java:355)
> 

```
Swagger2MarkupConfig config = new Swagger2MarkupConfigBuilder()
                .withMarkupLanguage(MarkupLanguage.ASCIIDOC)
                .withOutputLanguage(Language.DE)
                .withPathsGroupedBy(GroupBy.TAGS)
                .build();

Swagger2MarkupConverter.from(localSwaggerFile)
                .withConfig(config)
                .build()
                .toFolder(outputDirectory);
```

With MarkupLanguage.MARKDOWN is everyting ok.

**Comment by RobWin** [comment]
Hi,

do you have another dependency to the ASM library (http://asm.ow2.org/)?

**Comment by raderio** [comment]
Hi,

yeap, I have have another dependency to the ASM library version 5.
But swagger2markup uses version 4.
I have tested without dependency to the ASM library version and it's work.
Thanks.

**Comment by raderio** [comment]
> nl.jworks.markdown_to_asciidoc:markdown_to_asciidoc:1.0
> |    |         +--- org.pegdown:pegdown:1.4.2
> |    |         |    \--- org.parboiled:parboiled-java:1.1.6
> |    |         |         +--- org.parboiled:parboiled-core:1.1.6
> |    |         |         +--- org.ow2.asm:asm:4.1 -> 5.0.1
> |    |         |         +--- org.ow2.asm:asm-tree:4.1 -> 5.0.1 (*)
> |    |         |         +--- org.ow2.asm:asm-analysis:4.1
> |    |         |         |    \--- org.ow2.asm:asm-tree:4.1 -> 5.0.1 (*)
> |    |         |         \--- org.ow2.asm:asm-util:4.1
> |    |         |              \--- org.ow2.asm:asm-tree:4.1 -> 5.0.1 (*)

**Comment by raderio** [comment]
So, I have added
compile group: 'org.pegdown', name: 'pegdown', version: '1.6.0'
Before
compile group: 'io.github.swagger2markup', name: 'swagger2markup', version: '1.1.0'
And now it work

**Comment by RobWin** [comment]
Btw  if you like and use Swagger2Markup, we would love to get your GitHub star.

**Comment by RobWin** [comment]
thx

**Comment by manosbatsis** [comment]
Forcing pegdown 1.6.0 using an explicit dependency fixes the problem for maven.
