### ISSUE TITLE
Custom design

### ISSUE THREAD

**Issue by raderio** [Swagger2Markup/swagger2markup#209]
How to customize design?
I want to make something similar to https://dev.twitter.com/rest/reference/get/direct_messages/sent
So I need to customize some static pages and customize resource infoormation.

**Comment by RobWin** [comment]
Hi,

Swagger2Markup just generates Markdown or AsciiDoc without any design layout. You have to check the tool which you use to convert Markdown or AsciiDoc into HTML. 
For example, AsciiDoctor allows to customize CSS.
You could also use Jekyll to create a static site based on Markdown or AsciiDoc.
