### ISSUE TITLE
Support composed definitions

### ISSUE THREAD

**Issue by RobWin** [Swagger2Markup/swagger2markup#21]
Currently, if you have a composed definition (using the allOf device), no documentation is generated for that definition other than the header and description. This is because the current definition code does not take into account $refs or composition.

This adds support for both reference models and composed models. The composition logic could likely be improved to provide better documentation for the composition (i.e. - where the definition came from, etc.), but for this improvement just flattens the composed model in the documentation. I see this is a fine compromise given that's how the endpoint will behave, anyway.

**Comment by RobWin** [comment]
Released in v0.7.0

**Comment by tjulinfan** [comment]
Hi,

It seems not work for response schema using v0.7.0, here is the json file and the result.
![image](https://cloud.githubusercontent.com/assets/2167565/8666313/294e04d8-2a22-11e5-98bb-0a272b633e82.png)

![image](https://cloud.githubusercontent.com/assets/2167565/8666322/42f4a93c-2a22-11e5-8c1e-e94ac3142efa.png)

**Comment by RobWin** [comment]
Thx. I have a look at it.

**Comment by RobWin** [comment]
Hello, I remember why its not implemented.
The Respones table and the column `Schema` is not suited to render an inner table of all properties of the composed schema.
A better practice would be to create a new Model definition, e.g. `MyComposedRepsonse`, which composes your `#/definitions/Response` and your `registered` property. In your responses you just reference the MyResponse model `"$ref": "#/definitions/MyComposedResponse`

**Comment by RobWin** [comment]
I would love to get your GitHub Star, if you like Swagger2Markup.
