### ISSUE TITLE
Swagger markdown headings not translated correctly to asciidocs

### ISSUE THREAD

**Issue by bpaczkowski** [Swagger2Markup/swagger2markup#210]
Swagger2Markup version: 1.1.0

Problem description:
In my swagger definition I use markdown to specify headings in the resulting HTML doc like so: `#### Roles`, which results in a correct H4 heading in HTML. In asciidocs the swagger headings are moved one level down compared to the HTML swagger docs but the markdown headings remain the same which results in my `Roles` heading showing on the same level as path descriptions.

I believe a picture is worth more than a thousand words, so I'm posting a screenshot of what it looks like without edits to swagger def:
![acrord32_2016-11-15_20-14-27](https://cloud.githubusercontent.com/assets/1371800/20319958/6dccc77c-ab70-11e6-9d39-4d543532560b.png)
And after editing `#### Roles` to `##### Roles` (which I don't really want to do because then the swagger html docs will be messed up):
![acrord32_2016-11-15_20-15-04](https://cloud.githubusercontent.com/assets/1371800/20319968/73b5d6b0-ab70-11e6-8ebc-12273c2857cd.png)

**Comment by RobWin** [comment]
Hello,
thank you for using Swagger2Markup. If you like it, we would love to get your GitHub star.

Which tool do you use to generate your HTML swagger docs from Markdown? It does not look like swagger-ui?

**Comment by RobWin** [comment]
If you don't want to generate a static PDF documentation as well. 
You could have a look at https://github.com/Rebilly/ReDoc/.

**Comment by bpaczkowski** [comment]
It's inline markdown I put in the path description, swagger-ui converts it to HTML when parsing the definition file.

**Comment by RobWin** [comment]
The screenshots don't look like swagger-ui? Is it a mock-up to show the issue?

**Comment by bpaczkowski** [comment]
No, actually they are from Adobe Reader with the generated PDF from asciidocs open, I figured it would communicate my point better than plain asciidocs.

**Comment by RobWin** [comment]
Right now, we don't modify Markdown descriptions which are imported from Swagger specs.
We just convert Markdown descriptions to Asciidoc. We can't know if we should process Markdown descriptions before importing them
Swagger2Markup has an extensions SPI which can be used to add extension. For example to preprocess a Swagger spec before it is converted.
You could create a Swagger2Markup extensions, which customizes all descriptions to your needs.

http://swagger2markup.github.io/swagger2markup/1.1.0/#_extension_spi

**Comment by bpaczkowski** [comment]
Thank you, though I don't think I'll need it. I wont be converting my swagger docs very often and it may be just easier to do a search and replace for the markdown headers instead.

If this is not considered an issue then you can close this report now.

**Comment by RobWin** [comment]
Ok. Thx.
If you use Swagger2Markup, we would love to get your GitHub Star.
