### ISSUE TITLE
Cannot Convert From Swagger Document That Has Been Modularized 

### ISSUE THREAD

**Issue by prahim** [Swagger2Markup/swagger2markup#212]
Swagger2Markup version: "io.github.swagger2markup:swagger2markup:1.1.0"

I have a modularized swagger documentation in yaml. I am trying to read in my index.yaml that looks like:
`swagger: '2.0'
info:
  $ref: ./api/info/index.yaml
paths:
  $ref: ./api/paths/index.yaml
definitions:
  $ref: ./api/definitions/index.yaml
`

But this is not working -- I am getting a null pointer on the title which is located in info/index.yaml. Nothing from the other yaml files seem to get picked up. I tried absolute paths and it still doesn't alleviate the issue, although swagger works with the relative paths shown here.

**Comment by RobWin** [comment]
Hi,

thanks for using Swagger2Markup. If you like it, we would love to get your GitHub Star.

I have a look at your issue.

**Comment by RobWin** [comment]
I added a test, it works. Could you please show me how do you invoke Swagger2Markup?
Do you use a Plugin?

**Comment by RobWin** [comment]
Yes, the parsed Java Model does not contain the content of the referenced files.
Now, I have to investigate why the swagger-parser fails to parse the file correctly.
Maybe it does not support JSON references at that level.

**Comment by RobWin** [comment]
I opened an issue https://github.com/swagger-api/swagger-parser/issues/346

**Comment by RobWin** [comment]
What you have here is not legal based on https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md
You can only use `$ref` where Swagger 2.0 supports it.
