### ISSUE TITLE
Add ability to insert page breaks in certain positions

### ISSUE THREAD

**Issue by cascer1** [Swagger2Markup/swagger2markup#214]
I'd like to be able to set a configuration item to start certain sections on a new page.

For example: It should be possible to say that each new operation (path/method combination) has to start on a new page.

I believe this makes the document look much cleaner.

**Comment by RobWin** [comment]
Hi,

you mean something like Asciidoctors `<<<`?

**Comment by cascer1** [comment]
Exactly! 

I'm writing a program to convert RAML specs to PDF and found that the output looked much cleaner after starting each new method on a new page.

**Comment by RobWin** [comment]
How do you convert Raml to AsciiDoc? Do you use Swagger2Markup?

**Comment by cascer1** [comment]
I'm writing my own tool to convert raml to asciidoc. The repo is private but will be made public within a month probably

**Comment by RobWin** [comment]
Very nice.
Is the design similar to Swagger2Markup or different?

**Comment by cascer1** [comment]
It also generates asciidoc output, so in theory you could style it however you want. It also allows people to create there own templates (Using Nunjucks) for the rendered output.

[Here's a little sample](https://ducohosting.com/screenshots/isaacff12d145869d5949ab596645cb6e168b.png)


The only thing I'm still working out is resolving JSON schemas. The sample API spec I use (the original spec for [this page](https://developer.globalcollect.com/documentation/api/server/)) has some crazy nested JSON schemas and it isn't clear which parts are attributes and which are references to other objects.  After implementing that it'll be pretty much done.

**Comment by RobWin** [comment]
Looks nice.
If you want to support Asciidoc and Markdown, you could use https://github.com/Swagger2Markup/markup-document-builder instead of using a Template engine. 
But then people can create their own templates.

**Comment by cascer1** [comment]
That looks interesting. What kind of input does it use? I currently pass a JSON object to Nunjucks with all info.

**Comment by RobWin** [comment]
Its a standard Java buider (pattern) which consumes Strings:

```
MarkupDocBuilder builder = MarkupDocBuilders.documentBuilder(MarkupLanguage.ASCIIDOC);
        builder.documentTitle("Test title")
        .sectionTitleLevel1("Section Level 1a")
        sectionTitleLevel2("Section Level 2a")
        .paragraph("Paragraph with long text bla bla bla bla bla")
        .listing("Source code listing")
        .boldTextLine("Bold text line b")
        .italicTextLine("Italic text line b")
        .unorderedList(Arrays.asList("Entry1", "Entry2", "Entry 2"));
```
But you can even import Markdown und convert it into AsciiDoc. 

Swagger2Markup has a component-based design where are document is composed of components and a component can be composed of other components. A component uses the builder to create Markdown/AsciiDoc.

A simple example is the `ContactInfoComponent` which renders the information about a Swagger `Contact`. A component consumes the parsed Swagger Java Model.

**Comment by cascer1** [comment]
Thanks! I currently use the javascript version, but am seriously considering moving it over to java now :)

**Comment by RobWin** [comment]
👍
