### ISSUE TITLE
Path grouping via a RegEx pattern

### ISSUE THREAD

**Issue by cascer1** [Swagger2Markup/swagger2markup#215]
Hi!

I'm testing this tool using a large API spec (the [Globalcollect S2S API](https://developer.globalcollect.com/documentation/api/server/), to be specific), and having just one list of endpoints isn't very useful.

Instead, it would be awesome if I could define (for example) a RegEx pattern for headers, which is then used for grouping paths.

For example: The Globalcollect API has endpoints in categories like payments, payouts and products:

* POST {merchantId}/payments
* GET {merchantId}/payments/{id}
* POST {merchantId}/payments/{id}/approve
* POST {merchantId}/payments/{id}/cancel
* POST {merchantId}/payouts
* GET {merchantId}/payouts/{id}
* GET {merchantId}/products
* POST {merchantId}/products
* GET {merchantId}/products/{id}
* etc. (You get the idea).

In another tool I'm developing, I added the ability to match endpoints to a RegEx, and assign them to a category if they match, the categories are generated based on the first capture groups in the patterns. Using the example above, I then match them with RegEx `\/{merchantId}\/(\w+)$`

This results in the categories payments, payouts and products being created. All paths are then put inside these categories. This results in the following structure (All paths have a description so they can get a pretty name):

![image](https://ducohosting.com/screenshots/isaac89d5bd4be6584f355294bd9d30ce5aab.png)

A similar functionality in this tool would be awesome!

**Comment by RobWin** [comment]
Hello,

wow, the API docs web site of Globalcollect S2S API is awesome :)
Swagger2Markup does support that already using Swagger tags. See http://swagger2markup.github.io/spring-swagger2markup-demo/1.1.0/

**Comment by cascer1** [comment]
Hi,

The problem is that swagger tags require people to modify their API spec. I don't think globalcollect wants to pay someone to go through their entire spec and add tags to all paths. (Trust me, it's a large file) This would also allow for easy adjustment of headers to test different configurations too.

**Comment by RobWin** [comment]
Do they have a Swagger Spec?

**Comment by cascer1** [comment]
I'll have a look around the source code and try to cook something up :)

**Comment by RobWin** [comment]
👍  Thx

**Comment by cascer1** [comment]
@RobWin I've started working on this some more, could you have a look to see if I missed any methods required to make this work?  

https://github.com/Swagger2Markup/swagger2markup/compare/master...cascer1:feature/regex-path-grouping

Also, are there any unit tests for sorting? If so, I couldn't find them.

**Comment by RobWin** [comment]
@cascer1 There are two unit tests for sorting.

https://github.com/Swagger2Markup/swagger2markup/blob/master/src/test/java/io/github/swagger2markup/AsciidocConverterTest.java#L116

and 

https://github.com/Swagger2Markup/swagger2markup/blob/master/src/test/java/io/github/swagger2markup/AsciidocConverterTest.java#L143

**Comment by RobWin** [comment]
The commits look good so far.

**Comment by cascer1** [comment]
I believe this was closed by #217
