### ISSUE TITLE
Don't use schema name as example

### ISSUE THREAD

**Issue by cascer1** [Swagger2Markup/swagger2markup#219]
When one of the fields in a schema does not have an example in the Swagger spec, the Example line should simply be ignored.

Currently, I have some schemas that have fields referring to other schemas but no examples, the tool simply puts the schema name that it's referring to between quotation marks and calls it a day.

When reading the resulting document, it may be confusing to see a certain schema, but then see a String as example.

**Comment by RobWin** [comment]
Hi , do you mean when generateExamples is activated?

**Comment by cascer1** [comment]
Oh, I kind of assumed that without generateExamples, it wouldn't give me any examples (Including those that are defined in the spec)

**Comment by cascer1** [comment]
Actually, I still do see an issue:

When I don't use the `withGeneratedExamples()` config option, the definition tables still generate examples containing strings: 

![image](https://ducohosting.com/screenshots/isaacc33f6f9f36389d58c6ea1c497ed0b492.png)

**Comment by RobWin** [comment]
I can't reproduce that. Could you please show me your Swagger Spec?

**Comment by cascer1** [comment]
I'll modify the spec to remove any sensitive data and then I'll post it here.

**Comment by cascer1** [comment]
I just reviewed my code one more time and it seems I did mess something up, this issue is very invalid now.
