### ISSUE TITLE
Debug logging output should be set to log level Debug or Trace

### ISSUE THREAD

**Issue by cascer1** [Swagger2Markup/swagger2markup#220]
During execution of the code, the tool outputs all kinds of information to the INFO log, that is pretty irrelevant during normal execution.

![image](https://ducohosting.com/screenshots/isaac5e9450ee38211988fb2f122268bf7e57.png)

I believe the log level for this output should be set to debug, or even trace.

**Comment by RobWin** [comment]
Hi,

if you like you can change it to debug
