### ISSUE TITLE
Response example is not converted correctly

### ISSUE THREAD

**Issue by kegstyle** [Swagger2Markup/swagger2markup#223]
Swagger2Markup version: 1.1.0

Problem description:
When I tried to convert my test swagger file to adoc file, example of response was not converted correctly.
The mime type (ex. application/json) is represented in example json as a key.

This is my test swagger file.

        :
      responses:
        200:
          description: "successful operation"
          schema:
            type: array
            items:
              $ref: "#/definitions/Pet"
          examples:
            application/json:
            - id: 2331
              name: mungmung
              photoUrls:
                - url1
                - url2
              status: available

When I converted it then I got, 

    ===== Example HTTP response
    
    ====== Response 200
    [source,json]
    ----
    {
      "application/json" : [ {    <-- ??????
        "id" : 2331,
        "name" : "mungmung",
        "photoUrls" : [ "url1", "url2" ],
        "status" : "available"
      } ]
    }
    ----

But my expect is ...

    ===== Example HTTP response
    
    ====== Response 200
    [source,json]
    ----
    [
     {
        "id" : 2331,
        "name" : "mungmung",
        "photoUrls" : [ "url1", "url2" ],
        "status" : "available"
      } 
    ]
    ----

What's wrong with my configs?

Thanks
Esteban

**Comment by RobWin** [comment]
Hi,

nothing is wrong in your configuration.
I think we have to enhance the rendering of examples .

Btw if you like and use Swagger2Makup, we would love to get your GitHub star.

**Comment by kegstyle** [comment]
@RobWin Thanks for your comment. And I've given you start :)

**Comment by cascer1** [comment]
It looks like the problem is that the Swagger `Json.pretty()` method converts the example including content-type to a JSON object. The result of this method is a JSON object where the first key is the content-type (for your issue, this would be `application/json`) and the value of this key is the actual example. 

Converting the result of `Json.pretty()` to a Java array, and then printing the values only *should* do the trick.

**Comment by kegstyle** [comment]
When do you plan to release the next version(1.1.2 or 1.2) with this fix?
And I'm using "swagger2markup-gradle-plugin" also, but the plugin is now supporting swagger2markup version 1.1.0.
I wish the plugin also be updated with latest swagger2markup.

**Comment by RobWin** [comment]
Hi,

I release it soon, but you can already use it.
The Plugin is not coupled to a specific Swagger2markup version 
See https://github.com/Swagger2Markup/swagger2markup-gradle-project-template/blob/master/build.gradle#L11

**Comment by kegstyle** [comment]
Thanks a lot. :)
It works good.

**Comment by RobWin** [comment]
I published v1.2.0. You can use it now.
