### ISSUE TITLE
[Question] How can I remove the default response codes from generated doc

### ISSUE THREAD

**Issue by OllisGit** [Swagger2Markup/swagger2markup#224]
Swagger2Markup version: 
I am using the "spring-swagger2markup-demo" version"1.0.0" with "swagger2markup" version "1.0.1-SNAPSHOT"

Question:
After generating the "asciidoc\html\index.html" with "mvn clean package" the html shows all status codes ( 200, 400, 401, 403, 404) for "Find pet by ID".
But in the source code there is only the description for 400 and 404.
```
  @ApiResponses(value = {
          @ApiResponse(code = 400, message = "Invalid ID supplied"),
          @ApiResponse(code = 404, message = "Pet not found")}
  )
```
Is there a way to remove the unnecessary status codes. Something like "<swagger2markup.useDefaultResponseMessages>false</swagger2markup.useDefaultResponseMessages>" in pom file?

BR
Olli

**Comment by RobWin** [comment]
Hi,

Thx for using Swagger2Markup. If you like it, we would love to get your GitHub Star.
This must be configured in your Springfox configuration. The Docket builder allows to configure default Response codes.

**Comment by RobWin** [comment]
Did it work for you?

**Comment by OllisGit** [comment]
Sorry for the delay (x-mas break) and thanks for your fast response.
In my first approach I didn't realized that  "Swagger2Markup" is not responsible for creating the swagger.json file. The json-file is created via an "online" test-call.

I have no spring-boot and I need a "offline" solution, so now I used the Maven-Plugin "com.github.kongchen.swagger-maven-plugin" first, to create the swagger.json file.

But the most importend thing is, that  I use the code-Attribute in the APIOperation-Annotation if I want to remove the default 200 value

```
	@ApiOperation(code=201, value="updatePet")
	@ApiResponses(value = { 
			@ApiResponse(code = 201, message = "Pet succesfull updated"), 
			@ApiResponse(code = 400, message = "Invalid ID supplied"), 
			@ApiResponse(code = 404, message = "Pet not found") })

```
Thx, for your work
Olli

**Comment by RobWin** [comment]
Thx.
If you use Swagger2Markup, we would love to get your GitHub Star.
