### ISSUE TITLE
swagger-jersey2-jaxrs 1.5.12 isnt supported

### ISSUE THREAD

**Issue by timgold** [Swagger2Markup/swagger2markup#239]
Hi,
I am using swagger2markup version 1.2.0
When switching from swagger-jersey2-jaxrs version 1.5.10 to 1.5.12, i am unable to generate valid adocs of my swagger jsons.

I am receiving an exception similar to this:
Exception in thread "main" java.lang.NoSuchMethodError: io.swagger.models.parameters.AbstractSerializableParameter.getDefaultValue()Ljava/lang/String; 

for String, Double, Boolean etc.

here is a linked to someone with a similar issue:
https://github.com/swagger-api/swagger-core/issues/2095

swagger team said the issue is related to swagger2markup.

Is a fix planned in the near future? i badly need some of the features introduced in swagger version 1.5.12 along with the ability to generate an html document from the swagger jsons.

**Comment by RobWin** [comment]
Hi,

If you like and use Swagger2markup, we would love to get your GitHub Star.
This issue is related to #235. You can already try version 1.3.0-SNAPSHOT
