### ISSUE TITLE
Any way be used in jdk6 projects?

### ISSUE THREAD

**Issue by riddlegit** [Swagger2Markup/swagger2markup#24]
Swagger2markup is really really fun, coz we don't need to view api docs dynamictly, especially on a production envirement, we prefer to generate static docs any time we want, so swagger2markup will help a lot, I stared this project at the first sight.

Unfortunately all of our projects stay jdk6 because they are big and developed years ago, and I face the jdk compatibility problem when I try to run the swagger2markup unit test method to generate static docs, it's so sad...

**Comment by RobWin** [comment]
Hi, thx for the kind words.
You can also execute Swagger2Markup against a remote running Application. If you use Jenkins (or another build system), you could run Swagger2Markup (using JDK7) against an application which uses JDK6.

**Comment by riddlegit** [comment]
Hi RobWin, I'll have a try today later, thanks.

**Comment by RobWin** [comment]
Do you have a solution? Did my suggestion work for you?

**Comment by riddlegit** [comment]
Hi RobWin, sorry for late reply, I didn't find the way to run by Maven, is that work this kind of command directly?
mvn swagger2markup:process-swagger -PinputDirectory=http://<ip>:<port>/v2/api-docs

or I have to setup an empty project with JDK with plugin settings in pom.xml to run with Maven?

**Comment by RobWin** [comment]
@riddlegit You can use the Command Line Interface which is a community contribution.
https://swagger2markup.readme.io/docs/cli

**Comment by riddlegit** [comment]
Thanks, this command line interface may help :)
