### ISSUE TITLE
Bad multiline code block in AsciiDoc

### ISSUE THREAD

**Issue by mauricio-morales** [Swagger2Markup/swagger2markup#245]
Swagger2Markup version: 1.3.0

Problem description:
When including a multiline code block in a Description (as supported by Markdown) is mistranslated to AsciiDoc.

The Swagger YAML:
```
      description: "Example:
      
      ```

      curl -X GET -H \"Accept: application/json\" -H \"Authorization: Bearer <Your Token Here>\" \"https://my.api.com/Endpoint/00000000-0000-0000-0000-000000000000\"

      ```
      "
```

But Swagger2Markup tries to convert it into an inline code statement:
```
==== Description
Example:
`
curl -X GET -H &quot;Accept: application/json&quot; -H &quot;Authorization: Bearer &lt;Your Token Here&gt;&quot; &quot;https://my.api.com/Endpoint/00000000-0000-0000-0000-000000000000&quot;
`


```

And `asciidoctor-pdf` fails to parse it (rightfully).
It should:

* Use `----` instead of `
* Not HTML-escape the `&`, `<`, `>`, etc.

Generated output should be
```
==== Description
Example:
----
curl -X GET -H "Accept: application/json" -H "Authorization: Bearer <Your Token Here>" "https://my.api.com/Endpoint/00000000-0000-0000-0000-000000000000"
----
```

Full small Swagger Spec to reproduce the issue:

```
---
swagger: '2.0'
info:
  title: Bad Spec
  contact:
    name: Developer
    email: developer@company.com
  version: '1.0'
host: my.api.com
basePath: "/"
schemes:
- https
produces:
- application/json
paths:
  "/Endpoint":
    get:
      summary: Retrieves all folders for the current user.
      description: "Example:
      
      ```

      curl -X GET -H \"Accept: application/json\" -H \"Authorization: Bearer <Your Token Here>\" \"https://my.api.com/Endpoint/00000000-0000-0000-0000-000000000000\"

      ```
      "
      responses:
        '200':
          description: Success
```

**Comment by RobWin** [comment]
Hi,

Swagger2Markup uses this library to convert Markdown to AsciiDoc: https://github.com/bodiam/markdown-to-asciidoc

It seems the library does not interpret your Markdown as a Code Block.

Maybe there are some Windows, Linux line feed issues?
On which OS did you create the Swagger Spec and on which OS do you invoke the Swagger2Markup CLI?

**Comment by mauricio-morales** [comment]
All in Windows 10. If you run with the spec I posted here, is the output different from what I have?

(Attaching my local bad-swagger file in case encoding is a key player)

[bad-swagger.zip](https://github.com/Swagger2Markup/swagger2markup/files/814497/bad-swagger.zip)

**Comment by RobWin** [comment]
As a workaround. Do you have to use Markdown in your Swagger Spec?
You could also use AsciiDoc directly and change the config property `swagger2markup.swaggerMarkupLanguage` to `ASCIIDOC`.

**Comment by mauricio-morales** [comment]
Thanks. Well, I'd like my `curl` examples to show code-block like. 
I use the same swagger file to host a web site with Swagger -UI (generating this PDF is a temporary measure while our website is ready for public). I'm not sure that Swagger web UI supports `ASCIIDOC` descriptions.

**Comment by mauricio-morales** [comment]
You just motived me to play around some more, and discovered that an extra line will "fix" the issue:

```
      ```


      curl -X GET -H \"Accept: application/json\" -H \"Authorization: Bearer <Your Token Here>\" \"https://my.api.com/Endpoint/00000000-0000-0000-0000-000000000000\"


      ```
```

Now generates
```
----

curl -X GET -H "Accept: application/json" -H "Authorization: Bearer <Your Token Here>" "https://my.api.com/Endpoint/00000000-0000-0000-0000-000000000000"

----
```

**Comment by mauricio-morales** [comment]
So maybe it wasn't so much a bug but rather a mis-formatting on my part on the Markdown inside the Swagger doc.
If you agree, then we can close this issue. I've already added the extra lines to my swagger and I'm able to generate the PDF with no parsing errors.

**Comment by RobWin** [comment]
Thx for the Information
