### ISSUE TITLE
"Table of Contents" is localizable

### ISSUE THREAD

**Issue by mingchen** [Swagger2Markup/swagger2markup#249]
**Swagger2Markup version:**
1.3.1

**Problem description:**
When use gradle template project and change language other than english, the left siebar title "Table of Contents" is not translated,  it is not defined in https://github.com/Swagger2Markup/swagger2markup/blob/master/src/main/resources/io/github/swagger2markup/lang/labels_en.properties
should define it here then can be translated ?

**Comment by RobWin** [comment]
Hi,
the Table of Contents is not part of Swagger2Markup, but generated by Asciidoctor. 
Please open an issue in this project: https://github.com/asciidoctor/asciidoctor
