### ISSUE TITLE
Some sections should be broken into separate lines

### ISSUE THREAD

**Issue by who** [Swagger2Markup/swagger2markup#25]
swagger2markup generates the following URI scheme information:

```
=== URI scheme
Host: example.com
BasePath: /api
Schemes: HTTPS
```

However, because these lines are not hard returns, the actual interpretation of these lines is:

**URI scheme**
Host: example.comBasePath: /apiSchemes: HTTPS

This makes for some unsightly output when using asciidoctor to convert the adoc to HTML. 

How do we change the output which swagger2markup chooses, in order to customize the newlines for this section, and other sections like it? 

I'd like the section to render adocs which use the `+` symbol, signifying a hard break:

```
=== URI scheme
Host: example.com +
BasePath: /api +
Schemes: HTTPS +
```

**Comment by RobWin** [comment]
You must specify in your index.adoc or in the Gradle/Maven plugin the Asciidoctor attribute `hardbreaks`.
See https://swagger2markup.readme.io/docs/demo in Gradle.
Or in index.adoc you must add `:hardbreaks:`.

**Comment by who** [comment]
Good to know, thanks @RobWin !  I'm using swagger2markup-cli in conjunction with the npm module asciidoctorjs-cli, and I can pass the options for hardbreaks.

**Comment by RobWin** [comment]
You are welcome. A sample/demo/blog of your tech stack would be nice. I could add it to the documentation.
