### ISSUE TITLE
Customize the example output

### ISSUE THREAD

**Issue by saqibahmed515** [Swagger2Markup/swagger2markup#253]
## Add customization in the example output:
I have 5 responses in one of my API specs and I just want to show the example output of the response with code 200. I don't want to show examples of all the error responses. I might wanna show the example output of more than one output but not for all the outputs. 
Is there any way I can achieve this?

### Swagger2Markup version:
**1.3.1** using **CLI version** with jar and reading configuration from local config file

**Comment by RobWin** [comment]
Hi,

do you define your Swagger Specs by hand or is the Spec automatically generated?
You can add examples into the Swagger Spec directly. See: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/api-with-examples.json

**Comment by saqibahmed515** [comment]
I'm writing swagger specs by hand. I didn't add any examples in any of the responses. I do have schemas for all the responses. For example,

Yaml:
```      
responses:
        200:
          description: User LoggedIn Successfully
          schema:
            $ref: '#/definitions/userLoginResponse'
        401:
          description: Unauthorized. Username and/or password is incorrect
          schema:
            $ref: '#/definitions/401Out'
          
        405:
          description: HTTP Method Not Allowed
          
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorFormat'  
```
for this swagger code, with examples enabled in swagger2markup, the output asciidoc is:

```
===== Example HTTP response

====== Response 200
[source,json]
----
{
  "username" : "string",
  "roles" : [ "string" ],
  "token_type" : "string",
  "access_token" : "string",
  "expires_in" : 0,
  "refresh_token" : "string"
}
----


====== Response 401
[source,json]
----
{
  "timestamp" : 0,
  "status" : 0,
  "error" : "string",
  "message" : "string",
  "path" : "string"
}
----


====== Response 500
[source,json]
----
{
  "status" : {
    "enumType" : "string",
    "name" : "string"
  },
  "message" : "string"
}
----
```

I just want a switch in my properties where I can specify for swagger2markup that where I want examples and where I don't.

**Comment by RobWin** [comment]
Sry, that's not possible yet.

**Comment by saqibahmed515** [comment]
It's ok. Give me some pointer in the code where I can try to tweak it. 😄

**Comment by RobWin** [comment]
You can use this unit test to test your changes: https://github.com/Swagger2Markup/swagger2markup/blob/master/src/test/java/io/github/swagger2markup/AsciidocConverterTest.java#L305

Example generation starts here: https://github.com/Swagger2Markup/swagger2markup/blob/d2d47cf8eef17261202322782dbae62c2541454b/src/main/java/io/github/swagger2markup/internal/component/PathOperationComponent.java#L358

**Comment by saqibahmed515** [comment]
Thank you so much. 👍

**Comment by RobWin** [comment]
Can I close the issue?

**Comment by saqibahmed515** [comment]
Yeah sure. Close it. I couldn't find time to work on it.
