### ISSUE TITLE
*/* not escaped 

### ISSUE THREAD

**Issue by dcp65** [Swagger2Markup/swagger2markup#254]
Swagger2Markup version: 1.3.1

Problem description:

I am unable to re-open this issue #28, so I'm creating a new one here.

The fix for #28 is not enough for */* to be rendered correctly in HTML or PDF using AsciiDoc. If you try this in AsciiDocLive, you'll see that you need to add an escape character before the starting * symbol for it to render correctly.

\*/*

**Comment by RobWin** [comment]
Hi,
does a MediaType `*/*` really makes sense for an API?

**Comment by davidporter65** [comment]
An interesting philosophical question. Not sure that I'm qualified to answer it, but the wildcard media type is included in the JAX-RS spec, so we're bound to come across when documenting RESTful APIs:

http://docs.oracle.com/javaee/7/api/javax/ws/rs/core/MediaType.html#WILDCARD

**Comment by RobWin** [comment]
Is your Swagger Spec handcrafted or generated from code?

**Comment by davidporter65** [comment]
Generated from code

**Comment by RobWin** [comment]
Anyway it's a bug in Swagger2Markup, I'm just asking so that you have a workaround ;)

**Comment by RobWin** [comment]
A new SNAPSHOT version should be available now: `1.3.2-SNAPSHOT`. Do you use Maven/Gradle or CLI?
Can you try the new SNAPSHOT version and tell me if it works for you?

**Comment by davidporter65** [comment]
Many thanks. That works. 

I use Maven in some projects and Gradle in others. 

I wasn't sure how to get your snapshot, so I built from the swagger2markup source and installed it in my local Maven repo using the `publishToMavenLocal` Gradle task. 

I'll have to wait for a full release before I can consume it in my project. Any idea when the next release will be?

**Comment by RobWin** [comment]
How to get SNAPSHOTS is described in the user guide: http://swagger2markup.github.io/swagger2markup/1.3.1/#_snapshot

**Comment by dcp65** [comment]
@RobWin This is fixed now, right? Should the issue be closed?

**Comment by RobWin** [comment]
Don't remember 😐 Does it work? 😀

**Comment by dcp65** [comment]
I was waiting for the 1.3.2 release of the Gradle plugin.

**Comment by RobWin** [comment]
I had some problems with bintray while releasing. You can already use the new S2M 1.3.2 with the last gradle plugin. You can just overwrite the transitive dependency.

**Comment by RobWin** [comment]
See buildscript section in https://github.com/Swagger2Markup/swagger2markup-gradle-project-template/blob/master/build.gradle

**Comment by dcp65** [comment]
Great. That works. So this can be closed. Thanks

**Comment by RobWin** [comment]
Awesome. Thx
