### ISSUE TITLE
Security Schema does not include description

### ISSUE THREAD

**Issue by alkemann** [Swagger2Markup/swagger2markup#259]
The Swagger spec includes a description key, the schema for the security document in Swagger2Markup also has the key, but even if included in the provided swagger document, it is not included in the rendered output. I have made a Security Document Extension and verified that the description key is null, so I assume the problem is with the parser and not the output generation.

Swagger2Markup version: 1.3.1 & 1.3.2-SNAPSHOT

**Comment by RobWin** [comment]
Thx. Would you like to create an issue in the swagger-parser project.

**Comment by alkemann** [comment]
@RobWin I do not know how this project uses that project or how to tell them that the problem even exists in that place. I have tried to checkout the code and see if I can fix this myself, but I can't really figure out how the pieces fit together (I am not a java developer).

https://github.com/swagger-api/swagger-parser/issues/480  maybe you can add some specific information?
