### ISSUE TITLE
Definitions are not sorted alphabetically in the resulting asciidoc

### ISSUE THREAD

**Issue by zmitrok** [Swagger2Markup/swagger2markup#26]
Would be nice to have them sorted automatically and even to have a way to specify custom ordering.

**Comment by RobWin** [comment]
Yes, I add this feature after my vacation. If it is urgent, please create a PR. Should be easy to implement.
If you like Swagger2markup, I would love to get your GitHub Star :)

**Comment by RobWin** [comment]
PR is included in v0.8.0

**Comment by zmitrok** [comment]
It works, thank you.

**Comment by RobWin** [comment]
Thanks to you! I added you to the contribution chapter.
