### ISSUE TITLE
Cannot remove 'enums' section using SwaggerModelExtension

### ISSUE THREAD

**Issue by Eragra3** [Swagger2Markup/swagger2markup#270]
Hi,

I want to remove enums from one of my operation parameters and display that as a regular string. I created new SwaggerModelExtension, but
I don't see any method allowing me to get my hands on those enums. Is there a way to do it? If not it would be nice to have that.

Below is an example of a parameter I'd like to modify
```json
"/glass": {
  "get": {
    "tags": ["glassworks"],
    "summary": "Gets glass status",
    "description": "Short description",
    "operationId": "Glassy_1",
    "consumes": [],
    "produces": ["application/json", "text/json"],
    "parameters": [{
      "name": "glass",
      "in": "path",
      "description": "Describes glass state",
      "required": true,
      "type": "string",
      "enum": ["Empty", "Full", "Half empty", "Half full", "Indeterministic", "Why are we on this planet"]
    }],
    "responses": {
      "200": {
        "description": "OK",
        "schema": {
          "type": "object"
        }
      }
    }
  }
}
```
I want to remove enum property completely, so it's displayed as a bare string.

Kind regards
Daniel

**Comment by RobWin** [comment]
Hi,
could you please provide an example? I don't think that I understand what you want to achieve.

**Comment by Eragra3** [comment]
Hi,

sorry for lack of details, I updated question so it's more clear to future readers.

**Comment by RobWin** [comment]
You can remove the Enum, but you have to cast the parameter into the correct type.
```
List<Parameter> parameters = operation.getParameters();
// Select the correct parameter
PathParameter pathParameter = (PathParameter)parameter;
pathParameter.setEnumValue(null);
```

**Comment by Eragra3** [comment]
Hi again,

that's perfect, thank you for help!
I ended up using more general interface _SerializableParameter_ to support query params as well.

Thanks
Daniel

**Comment by RobWin** [comment]
:+1:

**Comment by RobWin** [comment]
@Eragra3 If you like Swagger2Markup, we would love to get your GitHub star :)

**Comment by Eragra3** [comment]
Like, favorite and subscribe? :)
Left a star for help ⭐️
