### ISSUE TITLE
Generating unique anchors for paths with the same operationId

### ISSUE THREAD

**Issue by Eragra3** [Swagger2Markup/swagger2markup#272]
Hi

we are using Swashbuckle in our application, which generates swagger from C# code. It generates multiple swagger endpoints for the same action if action is bound to multiple routes. That leads to duplicated operationIds.

> We are aware that operationId should be unique, that will be fixed in the future.

But for now, can we using some configuration or extension processors on swagger2markup to generate unique anchors for each endpoint? This is just to make table of content work. 
We cannot change operationId, because of dynamic file import ([this](http://swagger2markup.github.io/swagger2markup/1.3.1/#extension_import_files) thing).

Thanks for help
Daniel

**Comment by RobWin** [comment]
Hi,
did you find a solution for your problem? Did Swashbuckle fix the generation of operationIds?

**Comment by Eragra3** [comment]
I added new processor to Swagger2Markup which is generating unique operation ids based on current operation id and serialized list of arguments (parameters).

Swashbuckle is still generating same operation ids if you annotate actions with multiple **VersionedRoute**. Just pointing that out if somebody has that issue as well.
I think one could also add **IOperationFilter** (if I recall name correctly) to change how operation ids are generated, but I didn't try that.

**Comment by RobWin** [comment]
Would you like to create a PR for that functionality?

**Comment by Eragra3** [comment]
Absolutely! Though I am heavy on time currently, I won't be able to fix it quickly.
If nobody does that in the near future, expect me to create PR.
