### ISSUE TITLE
Patterned Objects not included in output

### ISSUE THREAD

**Issue by IAmWebSA** [Swagger2Markup/swagger2markup#277]
Swagger2Markup version: 1.3.1-cli

Problem description:

I am using Patterned Objects (see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#infoObject) 
x-custom-tag:
  - name: Additional Info
  - description: 'Some Stuff'

But the tool does not include it in the output file, only the standard tags are included.

How can this custom tags also be inlcuded?

**Comment by RobWin** [comment]
Hi,

Swagger2Markup has an extension SPI which you can use to add your own content. See: http://swagger2markup.github.io/swagger2markup/1.3.1/#_extension_spi

Patterned Objects cannot be added by default, because the type could be anything.
