### ISSUE TITLE
Failed to execute goal 'convertSwagger2markup' : text must not be blank

### ISSUE THREAD

**Issue by mayurchoubey** [Swagger2Markup/swagger2markup#278]
Swagger2Markup version: Tried with 1.3.1(latest), 1.0.1 both

Problem description:
Actually, I am using swagger maven plugin to create swagger.json of my SpringMVC Rest APIs and then using swagger2makup to convert swagger.json to asciidoc etc. 

Swagger maven plugin is able to generate swagger.json/yaml files but Swagger2Markup plugin is throwing "Failed to execute goal : text must not be blank" error.

Generate swagger yaml is attached as txt file. 

Would appreciate your help. 
Thanks in advance. 

[swagger.txt](https://github.com/Swagger2Markup/swagger2markup/files/1298620/swagger.txt)

**Comment by RobWin** [comment]
Hi,
could you please show me your stacktrace?

**Comment by RobWin** [comment]
I think your parameter names must not be empty.

**Comment by mayurchoubey** [comment]
[debug.zip](https://github.com/Swagger2Markup/swagger2markup/files/1306036/debug.zip)
PFA the stacktrace of mvn install. 
Here I have included both the cases success(petstore sample) and failure(my swagger json). 

Is there any documentation available to know mandatory fields etc. ?

**Comment by RobWin** [comment]
See the Specification: https://swagger.io/specification/#parameterObject
![image](https://user-images.githubusercontent.com/5815046/30479078-e2aaf522-9a13-11e7-883d-7dc17002cde1.png)

**Comment by RobWin** [comment]
Just one more informatione. You can see the full stack trace of  errors, if you run Maven with the -e switch.

**Comment by mayurchoubey** [comment]
Thanks... Parameter name was the missing link here...
