### ISSUE TITLE
Join multiple swagger json files and create one pdf/html5 static site

### ISSUE THREAD

**Issue by mayurchoubey** [Swagger2Markup/swagger2markup#279]
Swagger2Markup version: latest

Problem description:

I have multiple sub modules of maven in my product. There would be multiple sub modules exposing the rest apis. My requirement is to auto generate product documentation using swagger, swagger2markup and asciidoctor maven plugin. But could see swaggerInput tag can only take one file at a time. 

Confused how could I merge these multiple swagger jsons to achieve the goal?

Pls suggest. 

Thanks in advance.

**Comment by RobWin** [comment]
Hi,
do you want to generate an AsciiDoc documentation per sub module and merge them into one AsciiDoc documentation which documents several REST APIs?
You could create an `index.adoc` in the root project which includes all sub-module AsciiDoc files.
