### ISSUE TITLE
*/* not escaped

### ISSUE THREAD

**Issue by ejain** [Swagger2Markup/swagger2markup#28]
The following in Swagger:

    "produces": [
        "*/*"
    ]

...results in this asciidoc:

    ==== Produces
    
    * */*

...which is rendered as a bold slash.

**Comment by davidporter65** [comment]
This fix does not seem to be enough for `*/*` to be rendered correctly in HTML or PDF using AsciiDoc. If you try this in [AsciiDocLive](https://asciidoclive.com/), you'll see that you need to add an escape character before the starting `*` symbol for it to render correctly.

`\*/*`

I'm not sure if this is classed as a bug in AsciiDoc or if it's still a bug in Swagger2markup

**Comment by RobWin** [comment]
Hi, do you think you can provide a PR? I won't have much time atm to fix this.

**Comment by davidporter65** [comment]
@RobWin Sorry, I'm not a coder, just a doc writer. I don't know how to fix this.

I was just trying to establish whether this was still a bug in Swagger2markup or whether AsciiDoc should render markup inside back-ticks as is.
