### ISSUE TITLE
java.lang.NoSuchMethodError in ParameterUtils

### ISSUE THREAD

**Issue by gludington** [Swagger2Markup/swagger2markup#289]
Swagger2Markup version: 1.3.1

Problem description:
When attempting to run a generation test case:
` 
   @Test
    public void convertSwaggerToAsciiDoc() throws Exception {
        this.mockMvc.perform(get("/v2/api-docs?group=full-api")
                .accept(MediaType.APPLICATION_JSON))
                .andDo(Swagger2MarkupResultHandler
                        .outputDirectory("src/docs/asciidoc/generated").build())
                .andExpect(status().isOk());
    }
`

a NoSuchMethodError is thrown in ParameterUtils:
java.lang.NoSuchMethodError: io.swagger.models.parameters.AbstractSerializableParameter.getDefaultValue()Ljava/lang/String;

It appears getDefaultValue() was changed to return an object instead of a string  in swagger-core 1.5.11

https://github.com/swagger-api/swagger-core/blob/v1.5.11/modules/swagger-models/src/main/java/io/swagger/models/parameters/AbstractSerializableParameter.java

(Unfortunately, going back to swagger-core 1.5.10 is not an option, as other elements break with that revision.)

**Comment by gludington** [comment]
Update: after catching up with the changes around the projects, and getting around the version.  This bit of code replicates the pre-2.7.0 MockMvc test approach for springfox-swagger2 2.7.0, and swagger2markup- 1.3.1.  Placing here in case is it of any use to people.

`
    @Test
    public void convertSwaggerToAsciiDoc() throws Exception {

        Path outputDirectory = Paths.get("build/asciidoc");
        this.mockMvc.perform(get("/v2/api-docs?group=full-api")
                .accept(MediaType.APPLICATION_JSON))
                .andDo(new ResultHandler() {
                    @Override
                    public void handle(MvcResult result) throws Exception {
                        String swagger = result.getResponse().getContentAsString();
                        Swagger2MarkupConverter.from(swagger)
                                .build()
                                .toFolder(outputDirectory);
                    }
                })
                .andExpect(status().isOk());
    }
`

**Comment by MahatmaFatalError** [comment]
Is there any 'real' fix in the pipeline? I also stumbled upon this bug.

**Comment by china-fengguan** [comment]
same issue happened here, springfox-swagger2 v2.9.2 and springfox-staticdocs v2.6.1.
appriciate any help.
