### ISSUE TITLE
Tag descriptions rendered as tags

### ISSUE THREAD

**Issue by ejain** [Swagger2Markup/swagger2markup#29]
Given a Swagger spec with:

    "tags": [
        {
            "name": "foo",
            "description": "Foo"
        },
        {
            "name": "bar",
            "description": "Bar"
        }
    ]

The generated asciidoc has this redundant list of tags:

    === Tags
    
    * foo: Foo
    * foo
    * bar: Bar
    * bar

**Comment by RobWin** [comment]
Thx

**Comment by RobWin** [comment]
Fixed in v0.8.0

**Comment by RobWin** [comment]
Can I close the issue?

**Comment by ejain** [comment]
Works for me now, thanks!
