### ISSUE TITLE
installation question

### ISSUE THREAD

**Issue by rlauriston** [Swagger2Markup/swagger2markup#295]
Swagger2Markup version: to be determined

Problem description:
I'm a tech writer documenting some APIs written in Swagger YAML.
swagger2markup is distributed as a .jar file. The docs say to add the library to my project's classpath.
http://swagger2markup.github.io/swagger2markup/1.3.1/#_getting_started
I find no classpath setting or .jar files in the Swagger projects, nor is there a classpath environment variable (OS X 10.12.6), though npm start works fine.

**Comment by rlauriston** [comment]
@RobWin you closed this issue but looking at the docs I still don't know what to do. I asked about this on stackoverflow.com and got no answer there, either.
https://stackoverflow.com/questions/47912788/what-is-how-do-you-set-the-classpath-for-swagger2markup

**Comment by RobWin** [comment]
Hi, what do you mean by Swagger projects? Do you have experience in using Java? What do you want to do? You don't need npm for Swagger2Markup.

**Comment by rlauriston** [comment]
@RobWin I'm just quoting your doc:

> Swagger2Markup is a standard .jar file. To start using it, you need to add the library to your project’s classpath.

I'm not writing the API, just documenting it. All I did on my system was install Node.js, clone the Swagger repos, and run npm install. Then I can do npm start to use swagger-editor and swagger-ui. Do I need to install some more things to use swagger2markup?

**Comment by RobWin** [comment]
Swagger2Markup is a Java project. You can't install and it using JavaScript tools easily.
You can either download the Swagger2Markup docker image and convert your Swagger Spec or the CLI jar file and run it via a terminal. But you need to install Java in order to use the CLI. Please read the user guide for CLI or the docker image.

**Comment by rlauriston** [comment]
Thanks, swagger2markup-cli version is working fine for me.

**Comment by RobWin** [comment]
Awesome. We would love to get your GitHub star.

**Comment by mymmoonoa** [comment]
newbie to Java, after 3 hours of trying to run this program on MacOS, still I didn't make it.

Hope @RobWin can write a guide on how to setup and run this program.
And maybe it's better to add https://github.com/Swagger2Markup/swagger2markup-cli in the home ReadME.md
