### ISSUE TITLE
Issue in running on Springboot

### ISSUE THREAD

**Issue by akhileshtripa** [Swagger2Markup/swagger2markup#297]
Swagger2Markup version: 

Problem description: I am trying to setup a desk to demonstrate markdown documentation of my Swagger documents. But not sure how to run the app. Can you please help me with step by step idea on running this app.

**Comment by RobWin** [comment]
Hi, did you have a look at https://github.com/Swagger2Markup/spring-swagger2markup-demo

**Comment by akhileshtripa** [comment]
Thanks @RobWin, I tried to run the demo and able to run it. 
However, I want your help in generating markdown & ascii docs by importing a swagger file(yaml or json). The typical use case is that we are the part of api gateway team wherein we write swagger contract and those swagger contracts are being documented by the content writers for getting used by SoR ( System of Records) and BEs.

**Comment by RobWin** [comment]
There are two template projects which you can use to convert a Swagger Spec into asciidoc or markdown. One for maven and one for gradle. You could also use the CLI or docker image. Did you read the user guide?

**Comment by RobWin** [comment]
Can I close the issue?

**Comment by akhileshtripa** [comment]
Thanks @RobWin. Please close
