### ISSUE TITLE
Override/disable "URI scheme"

### ISSUE THREAD

**Issue by ejain** [Swagger2Markup/swagger2markup#30]
When using an integration test to generate asciidocs, the "host" is always "localhost". Should be able to override that, or at least disable the "URI scheme" section in the output.

**Comment by RobWin** [comment]
Thx.

**Comment by RobWin** [comment]
As a temp solution you could create a custom overview.adoc and include into the Index.adoc

**Comment by RobWin** [comment]
Have a look at #27.
With the upcoming version 0.8.0 you can preprocess the Swagger Model and customize it to your needs.

**Comment by RobWin** [comment]
Maybe I can add a "cleaner" builder method in a future release. But I'm at parental leave atm.

**Comment by RobWin** [comment]
If you like Swagger2markup, I would love to get your GitHub Star.

**Comment by RobWin** [comment]
Can I close the issue?

**Comment by codebusta** [comment]
Hi, have you solved this issue yet?

**Comment by RobWin** [comment]
Hi, 
yes. Using Swagger2Markup 1.0.0 you can create custom extension and modify the Swagger Model before it is processed. See documentation:

http://swagger2markup.github.io/swagger2markup/1.0.1-SNAPSHOT/#_swaggermodelextension

The following shows how to create and register a custom extension:

http://swagger2markup.github.io/swagger2markup/1.0.1-SNAPSHOT/#_creation_of_an_extension

**Comment by dagi12** [comment]
Any updates on this? Would be nice if swagger2markup would use `host` and `basePath` property  to create URI scheme without need of create any extension.
