### ISSUE TITLE
ch.netzwerg:paleo-core:0.10.2 and nl.jworks.markdown_to_asciidoc:markdown_to_asciidoc:1.0 not foud

### ISSUE THREAD

**Issue by shubifeng** [Swagger2Markup/swagger2markup#300]
Swagger2Markup version: 1.3

Problem description: maven install, no found class

![default](https://user-images.githubusercontent.com/6796352/36072124-4e8a3b5c-0f55-11e8-88d0-a90ccaa201d3.png)

**Comment by RobWin** [comment]
Some of the dependencies are not available in Maven Central.
Did you add JCenter as described in the user guide? http://swagger2markup.github.io/swagger2markup/1.3.1/#_release_2

**Comment by shubifeng** [comment]
@RobWin the must be define setting mirror for maven conf.   why not move the jar to maven central?

**Comment by RobWin** [comment]
Because the two other projects are not my projects.

**Comment by micobarac** [comment]
I added jcenter:

```
<repositories>
    <repository>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
        <id>jcenter-releases</id>
        <name>jcenter</name>
        <url>http://jcenter.bintray.com</url>
    </repository>
</repositories>
```

but I get this error:

```
[WARNING] The POM for nl.jworks.markdown_to_asciidoc:markdown_to_asciidoc:jar:1.0 is missing, no dependency information available
[WARNING] The POM for ch.netzwerg:paleo-core:jar:0.11.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.126 s
[INFO] Finished at: 2019-07-09T15:45:26+02:00
[INFO] Final Memory: 26M/228M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project open-provider: Could not resolve dependencies for project com.logate.openprovider:open-provider:war:2.1.2: The following artifacts could not be resolved: nl.jworks.markdown_to_asciidoc:markdown_to_asciidoc:jar:1.0, ch.netzwerg:paleo-core:jar:0.11.0: Failure to find nl.jworks.markdown_to_asciidoc:markdown_to_asciidoc:jar:1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
```

**Comment by micobarac** [comment]
This worked, after two days of frustration:

```
    <repositories>
        <repository>
            <id>spring-libs-milestone</id>
            <url>https://repo.spring.io/libs-milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <!-- jhipster-needle-maven-repository -->
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>spring-plugins-release</id>
            <url>https://repo.spring.io/plugins-release</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
```

**Comment by RobWin** [comment]
Very strange. Thanks for checking it.

**Comment by ylxbcoding** [comment]
> Finally, this worked, after two days of frustration:
> 
> ```
>     <repositories>
>         <repository>
>             <id>spring-libs-milestone</id>
>             <url>https://repo.spring.io/libs-milestone</url>
>             <snapshots>
>                 <enabled>false</enabled>
>             </snapshots>
>         </repository>
>         
>     </repositories>
> 
>     <pluginRepositories>
>         <pluginRepository>
>             <id>spring-plugins-release</id>
>             <url>https://repo.spring.io/plugins-release</url>
>             <snapshots>
>                 <enabled>false</enabled>
>             </snapshots>
>         </pluginRepository>
>     </pluginRepositories>
> ```
> 
> These two **swagger2markup** plugins were constantly being unresolved and **swagger2markup** couldn't have worked:
> [markdown_to_asciidoc](https://mvnrepository.com/artifact/nl.jworks.markdown_to_asciidoc/markdown_to_asciidoc/1.0)
> [paleo-core](https://mvnrepository.com/artifact/ch.netzwerg/paleo-core/0.11.0)
> 
> Analyzing [Maven Repository](https://mvnrepository.com/), these two problematic **swagger2markup** plugins were actually indexed by [Spring Plugins Repository](https://mvnrepository.com/repos/springio-plugins-release) repository.
> 
> The suggested [JCenter](https://mvnrepository.com/repos/jcenter) repository seemed outdated and did not work for me!

thank you, this helped me!!!

**Comment by Deep-Heart** [comment]
> Finally, this worked, after two days of frustration:
> 
> ```
>     <repositories>
>         <repository>
>             <id>spring-libs-milestone</id>
>             <url>https://repo.spring.io/libs-milestone</url>
>             <snapshots>
>                 <enabled>false</enabled>
>             </snapshots>
>         </repository>
>         
>     </repositories>
> 
>     <pluginRepositories>
>         <pluginRepository>
>             <id>spring-plugins-release</id>
>             <url>https://repo.spring.io/plugins-release</url>
>             <snapshots>
>                 <enabled>false</enabled>
>             </snapshots>
>         </pluginRepository>
>     </pluginRepositories>
> ```
> 
> These two **swagger2markup** plugins were constantly being unresolved and **swagger2markup** couldn't have worked:
> [markdown_to_asciidoc](https://mvnrepository.com/artifact/nl.jworks.markdown_to_asciidoc/markdown_to_asciidoc/1.0)
> [paleo-core](https://mvnrepository.com/artifact/ch.netzwerg/paleo-core/0.11.0)
> 
> Analyzing [Maven Repository](https://mvnrepository.com/), these two problematic **swagger2markup** plugins were actually indexed by [Spring Plugins Repository](https://mvnrepository.com/repos/springio-plugins-release) repository.
> 
> The suggested [JCenter](https://mvnrepository.com/repos/jcenter) repository seemed outdated and did not work for me!

Above answer is very useful for me, thanks very much.

**Comment by wl03094819** [comment]
> Finally, this worked, after two days of frustration:
> 
> ```
>     <repositories>
>         <repository>
>             <id>spring-libs-milestone</id>
>             <url>https://repo.spring.io/libs-milestone</url>
>             <snapshots>
>                 <enabled>false</enabled>
>             </snapshots>
>         </repository>
>         
>     </repositories>
> 
>     <pluginRepositories>
>         <pluginRepository>
>             <id>spring-plugins-release</id>
>             <url>https://repo.spring.io/plugins-release</url>
>             <snapshots>
>                 <enabled>false</enabled>
>             </snapshots>
>         </pluginRepository>
>     </pluginRepositories>
> ```
> 
> These two **swagger2markup** plugins were constantly being unresolved and **swagger2markup** couldn't have worked:
> [markdown_to_asciidoc](https://mvnrepository.com/artifact/nl.jworks.markdown_to_asciidoc/markdown_to_asciidoc/1.0)
> [paleo-core](https://mvnrepository.com/artifact/ch.netzwerg/paleo-core/0.11.0)
> 
> Analyzing [Maven Repository](https://mvnrepository.com/), these two problematic **swagger2markup** plugins were actually indexed by [Spring Plugins Repository](https://mvnrepository.com/repos/springio-plugins-release) repository.
> 
> The suggested [JCenter](https://mvnrepository.com/repos/jcenter) repository seemed outdated and did not work for me!

Thank you!!!

**Comment by JackyDFu** [comment]
> 
> 
> Finally, this worked, after two days of frustration:
> 
> ```
>     <repositories>
>         <repository>
>             <id>spring-libs-milestone</id>
>             <url>https://repo.spring.io/libs-milestone</url>
>             <snapshots>
>                 <enabled>false</enabled>
>             </snapshots>
>         </repository>
>         
>     </repositories>
> 
>     <pluginRepositories>
>         <pluginRepository>
>             <id>spring-plugins-release</id>
>             <url>https://repo.spring.io/plugins-release</url>
>             <snapshots>
>                 <enabled>false</enabled>
>             </snapshots>
>         </pluginRepository>
>     </pluginRepositories>
> ```
> 
> These two **swagger2markup** plugins were constantly being unresolved and **swagger2markup** couldn't have worked:
> [markdown_to_asciidoc](https://mvnrepository.com/artifact/nl.jworks.markdown_to_asciidoc/markdown_to_asciidoc/1.0)
> [paleo-core](https://mvnrepository.com/artifact/ch.netzwerg/paleo-core/0.11.0)
> 
> Analyzing [Maven Repository](https://mvnrepository.com/), these two problematic **swagger2markup** plugins were actually indexed by [Spring Plugins Repository](https://mvnrepository.com/repos/springio-plugins-release) repository.
> 
> The suggested [JCenter](https://mvnrepository.com/repos/jcenter) repository seemed outdated and did not work for me!

Helped a lot, thank you very much!

**Comment by zhouyun885** [comment]
How did it work out?
![Uploading image.png…]()

**Comment by DanielFran** [comment]
@zhouyun885 Those 2 dependencies no longer exists also in spring repository, so now the use of this plugin with the current version is not working.

cc @RobWin

**Comment by xieus** [comment]
Hit the same issue. Adding the Jcenter repo as suggested in https://github.com/Swagger2Markup/swagger2markup-maven-plugin/issues/37 can compile while Jcenter is not update to date. 

Any suggestion? @RobWin

**Comment by IvMikheev** [comment]
@zhouyun885 @xieus I used repositories and pluginRepositories blocks from here and it helped https://github.com/Swagger2Markup/spring-swagger2markup-demo/blob/master/pom.xml#L33-L63
