### ISSUE TITLE
The multi-tags of java class， but found only one tags at html

### ISSUE THREAD

**Issue by shubifeng** [Swagger2Markup/swagger2markup#302]
当多个tags时 生成html 没有只有一个tags， 而tags=“xxxxxxxxxxxx”则无法进行解析！
![default](https://user-images.githubusercontent.com/6796352/36672346-e00bc664-1b39-11e8-9433-c5209d430271.png)

html：
![default](https://user-images.githubusercontent.com/6796352/36672464-4d41d750-1b3a-11e8-800c-aff6015e0249.png)

**Comment by RobWin** [comment]
You grouped endpoints by tags. See your property `swagger2markup.pathsGroupedBy=TAGS`
You can only assign ONE tag per endpoint, if you want to group by tags.
Otherwise use `swagger2markup.pathsGroupedBy=AS_IS`.
