### ISSUE TITLE
Combining input folder with output file means last file processed wins

### ISSUE THREAD

**Issue by muddysteel** [Swagger2Markup/swagger2markup#304]
Swagger2Markup version: 1.3.4

Problem description:  If you configure the plugin to process a folder AND you supply an output file name, then the last file in the folder to be processed is the only one with content.

Just forked/fixed and created pull request

**Comment by RobWin** [comment]
Thx. I hope I can review it next week.

**Comment by muddysteel** [comment]
The update to Maven plugin fixes this.
