### ISSUE TITLE
Authentication info isn't included in the markup

### ISSUE THREAD

**Issue by zmitrok** [Swagger2Markup/swagger2markup#31]
I have a Basic Auth blurb in my Swagger JSON, and I can't see it in the resulting Asciidoc output.

**Comment by RobWin** [comment]
Yes. Security output is not implemented yet, because I believe that a security chapter should be written by hand. This is why I implemented Swagger2markup to mix Swagger with hand-written documentation.
But a PR is welcome, if you need it.

**Comment by RobWin** [comment]
Implemented in #63

**Comment by RobWin** [comment]
Will be supported in the upcoming release v0.9.3
