### ISSUE TITLE
Release version 1.3.3

### ISSUE THREAD

**Issue by kidnme** [Swagger2Markup/swagger2markup#310]
I don't know when new versions are released and what criteria is used to release them, but I'd certainly like to see a 1.3.3 and a new swagger2markup maven plugin release as well.

**Comment by RobWin** [comment]
Hi, the criteria is just my time :(
I try to release a new version as soon as possible.

**Comment by RobWin** [comment]
v1.3.3 of Swagger2Markup has been released.
I release the maven plugin soon.
But you can already use the new version with the old plugin if required.

**Comment by RobWin** [comment]
Maven Plugin v1.3.6 has been released.
