### ISSUE TITLE
Can't convert Swagger document containing nested arrays

### ISSUE THREAD

**Issue by johanhammar** [Swagger2Markup/swagger2markup#33]
I have a Swagger document containing nested arrays and when converting it it fails with a null pointer: java.lang.NullPointerException: property must not be null!

Here's an example Swagger file that will fail

```
swagger: '2.0'

info:
  version: "0.0.1"
  title: Nested arrays
  description: Demo of nested arrays
  contact:
    name: Johan Hammar

host: localhost

schemes:
  - https

basePath: /v1
produces:
  - application/json
consumes:
  - application/json

paths:
  /demo:
    get:
      tags:
        - Demo
      summary: Nested arrays demo
      description: |
        
      responses:
        200:
          description: Nested array object
          schema:
            type: object
            $ref: '#/definitions/nested'
definitions:              
  nested:
    properties:
      nested_array:
        type: array
        items: 
          properties:
            first_value:
              type: string
            second_value:
              type: string
```

However if I split the inner model to it's own model and reference it from the outer array it works. 

```
...
nested:
    properties:
      nested_array:
        type: array
        items:
          $ref: '#/definitions/inner'
  inner:
    properties:
            first_value:
              type: string
            second_value:
              type: string
```

I'm not sure if the first example is valid but it does render correctly in the [Swagger editor](http://editor.swagger.io)

**Comment by RobWin** [comment]
This seems to be an issue with the swagger-parser or swagger-model.

**Comment by RobWin** [comment]
Did you open an issue against swagger-parser?

**Comment by johanhammar** [comment]
I haven't yet. But I did some more investigation and I'm not quite sure my definition is valid.

I changed 

```
definitions:              
  nested:
    properties:
      nested_array:
        type: array
        items: 
          properties:
            first_value:
              type: string
            second_value:
              type: string
```

to (note the "type: object" declaration)

```
definitions:              
  nested:
    properties:
      nested_array:
        type: array
        items: 
          type: object
          properties:
            first_value:
              type: string
            second_value:
              type: string
```

The change made the Swagger2markup conversion not to fail but it did not render the definition correct.

I'll have to investigate a bit more

**Comment by johanhammar** [comment]
I've narrowed it down a bit, created a smaller Swagger document. Here is what happens if I try to convert the Swagger file

```
swagger: '2.0'
info:
  version: "0.0.1"
  title: Nested arrays
paths:
  /demo:
    get:
      responses:
        200:
          description: Nested array object
          schema:
            type: object
            $ref: '#/definitions/nested'
definitions:              
  nested:
    properties:
      nested_array:
        type: array
        items:
          type: object 
          properties:
            first_value:
              type: string
            second_value:
              type: string
```

The generated definitions.adoc looks like this

```
== Definitions
=== nested
[options="header"]
|===
|Name|Description|Required|Schema|Default
|nested_array||false|object array|
|===
```

Which doesn't contain the properties for the inner object. 

I'm still not sure what is the correct way to describe nested arrays in Swagger (without splitting each inner array into separate definitions). Anyway, both editor.swagger.io and swagger-parser seem to be ok with the Swagger file.

**Comment by RobWin** [comment]
Ok. Thx. The properties of the inner object are not shown because swagger2markup does not support inner tables yet. Therefore it would be better to split the definitions and create a separate Definition for the inner object.

**Comment by ronsmits** [comment]
I am running into this issue too. And I think it is quite a valid usecase where an object contains (an array of) objects. Would it not be possible to make the reference in the schema to the inner object something like a link to the definition of that object? Basically only make a ref to it?


Name | Type
------- | ------
 Name | String
Id|Integer
goal| #ref to goal object

The goal object:

Name | Type
------- | ------
|goal|String|
|id|Integer|

**Comment by RobWin** [comment]
Yes, but atm it is only possible if you create the #ref in your Swagger file by your own.

**Comment by ronsmits** [comment]
Hmmz just having spent quite some time in annotating all the code with swagger, now you want me to  start creating them myself ROFL

**Comment by RobWin** [comment]
Do you use Springfox?

**Comment by ronsmits** [comment]
I use the swagger-maven-plugin with JAX-RS in a JEE environment (tomee).

**Comment by RobWin** [comment]
Do you have a one to many relationship between two Models? Do you use a List or Arrays?

**Comment by ronsmits** [comment]
````

    @ManyToOne(cascade = CascadeType.ALL)
    private Goal parent;

    @OneToMany(mappedBy = "parent")
    private List<Goal> subGoals;
````

Its a birectional relationship

**Comment by RobWin** [comment]
Oh, its some sort of composite pattern. Does the swagger-maven-plugin support it? How does the generated Swagger look like?

**Comment by ronsmits** [comment]
I take it you only want the "definitions" part

````
"definitions" : {
    "Goal" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "integer",
          "format" : "int64"
        },
        "ownerEmail" : {
          "type" : "string"
        },
        "targetDate" : {
          "type" : "string",
          "format" : "date-time"
        },
        "reachedDate" : {
          "type" : "string",
          "format" : "date-time"
        },
        "title" : {
          "type" : "string"
        },
        "description" : {
          "type" : "string"
        },
        "subGoals" : {
          "type" : "array"
        }
      }
    }
````

**Comment by RobWin** [comment]
Two findings:
1. The subGoals array has not items specified. The item should be a $ref to the goal definition .
```
items:
          $ref: '#/definitions/Goal
```

2. I can't find the `parent` property?

**Comment by ronsmits** [comment]
The parent getter is set to @XmlTransient. Which is why it is not being picked up by swagger.

**Comment by RobWin** [comment]
Ok. If you add the items, it should be rendered as a link to the model definition.

**Comment by RobWin** [comment]
@ronsmits If you use and like Swagger2markup, I would love to get your GitHub Star.

**Comment by ronsmits** [comment]
I sorted it by using the newest version of the swagger maven plugin it all works fine now, thanks for your help and patience

**Comment by RobWin** [comment]
You are welcome.
