### ISSUE TITLE
how to combine multiple .adoc file to a single .adoc without using include

### ISSUE THREAD

**Issue by Hackniu** [Swagger2Markup/swagger2markup#334]
Thanks for raising a Swagger2Markup issue. Please provide a brief description of your problem along with the Swagger2Markup version you are using. If possible, please also consider putting together a complete Swagger specification that reproduces the issue. It's better if the Swagger specification is small and isolate the issue.

Swagger2Markup version:

Problem description:
I need to combine multiple .adoc to a single .adoc file, but i don't want to use "include". Is there another way to do it? thx!

**Comment by RobWin** [comment]
Hi, the other adoc files are not generated by Swagger2Markup?

**Comment by Hackniu** [comment]
there are four adoc files that have been generated by Swagger2Markup, and I want to combine these four files into a single adoc file.

**Comment by Hackniu** [comment]
great, thx!
