### ISSUE TITLE
Feature request: show enum values as examples

### ISSUE THREAD

**Issue by dlidstrom** [Swagger2Markup/swagger2markup#339]
I see that the examples being generated in markdown do not correspond to what I see in the Swagger file.

Swagger2Markup version: swagger2markup-cli-1.3.3.jar

Problem description:

Here's a minimum Swagger file:

```
{
    "swagger": "2.0",
    "info": {
        "version": "v1",
        "title": "SomeTitle"
    },
    "host": "some-host",
    "schemes": ["http"],
    "paths": {
        "/api/v{version}/FeatureToggle/All": {
            "get": {
                "tags": ["FeatureToggle"],
                "operationId": "FeatureToggle_GetAll",
                "consumes": [],
                "produces": ["application/json", "text/json", "text/html"],
                "parameters": [{
                    "name": "version",
                    "in": "path",
                    "required": true,
                    "type": "string"
                }],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/QueryResult[OrganizationFeatureToggle[]]"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "QueryResult[OrganizationFeatureToggle[]]": {
            "type": "object",
            "properties": {
                "QueryData": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OrganizationFeatureToggle"
                    }
                }
            }
        },
        "OrganizationFeatureToggle": {
            "type": "object",
            "properties": {
                "FeatureToggleKey": {
                    "format": "int32",
                    "enum": [2, 3, 4, 5, 6, 7, 11, 16],
                    "type": "integer"
                }
            }
        }
    }
}
```

config.properties looks like this:

```
swagger2markup.markupLanguage=MARKDOWN
swagger2markup.generatedExamplesEnabled=true
```

I run the conversion as follows:

java -jar $jar convert --config config.properties --swaggerInput input.json --outputFile out

Here's the output file, out.md, where I would like to see the enum values given as examples:

# SomeTitle

<a name="overview"></a>
### Version information
*Version* : v1

### URI scheme
*Host* : some-host  
*Schemes* : HTTP

<a name="paths"></a>
## Paths

<a name="featuretoggle_getall"></a>
#### Parameters

|Type|Name|Schema|
|---|---|---|
|**Path**|**version**  <br>*required*|string|

#### Responses

|HTTP Code|Description|Schema|
|---|---|---|
|**200**|OK|[QueryResult[OrganizationFeatureToggle[]]](#queryresult-organizationfeaturetoggle)|

#### Produces

* `application/json`
* `text/json`
* `text/html`

#### Tags

* FeatureToggle

##### Request path
```
/api/vstring/FeatureToggle/All
```

##### Response 200
```json
{
  "QueryData" : [ {
    "FeatureToggleKey" : 0
  } ]
}
```

<a name="definitions"></a>
## Definitions

<a name="organizationfeaturetoggle"></a>
### OrganizationFeatureToggle

|Name|Description|Schema|
|---|---|---|
|**FeatureToggleKey**  <br>*optional*|**Example** : `0`|integer (int32)|

<a name="queryresult-organizationfeaturetoggle"></a>
### QueryResult[OrganizationFeatureToggle[]]

|Name|Description|Schema|
|---|---|---|
|**QueryData**  <br>*optional*|**Example** : `[ "[organizationfeaturetoggle](#organizationfeaturetoggle)" ]`|< [OrganizationFeatureToggle](#organizationfeaturetoggle) > array|

# Summary 
As you can see, the example given is `0`. But it could be better, given that the Swagger file has examples as `[2, 3, 4, 5, 6, 7, 11, 16]`. I'm attaching the files for you.

[Problem.zip](https://github.com/Swagger2Markup/swagger2markup/files/2404613/Problem.zip)

**Comment by MarosPataky** [comment]
Hi @dlidstrom, is this something you'd still like to have?

@dlidstrom I could have a look, from my quick research it looks like there is no support for enums in "Integer" type. I could try to add that.

**Comment by MarosPataky** [comment]
@dlidstrom  Do you think something like this would be good?

### OrganizationFeatureToggle
|Name|Description|Schema|
|---|---|---|
|**FeatureToggleKey**  <br>*optional*|**Example** : `2`|enum (2, 3, 4, 5, 6, 7, 11, 16)|

**Comment by dlidstrom** [comment]
That looks fine @MarosPataky. This would help me just a little bit and I appreciate the effort. Thanks!

**Comment by MarosPataky** [comment]
@dlidstrom  Feel free to suggest any improvements. I'll open a PR for the changes I proposed in previous comment today.

**Comment by MarosPataky** [comment]
@RobWin Can we close this issue then?

**Comment by RobWin** [comment]
Yes, but we have to add it to the release notes file.
