### ISSUE TITLE
In GroupedBy.AS_IS, AS_IS stands for what?

### ISSUE THREAD

**Issue by Yuanxiangz** [Swagger2Markup/swagger2markup#362]
Thanks for raising a Swagger2Markup issue. Please provide a brief description of your problem along with the Swagger2Markup version you are using. If possible, please also consider putting together a complete Swagger specification that reproduces the issue. It's better if the Swagger specification is small and isolate the issue.

Swagger2Markup version:

Problem description:
hi, i am using swagger3markup. in reference docs, i didn't find any description about what does 'GroupedBy.AS_IS' mean. I can understand GroupedBy.Tags, GroupedBy.REGEX. but AS_IS stands for what?

**Comment by RobWin** [comment]
As specified in your swagger.json or swagger.yaml file.
No grouping will be done with AS_IS

**Comment by Yuanxiangz** [comment]
thank you!
