### ISSUE TITLE
Rest params reordered after every build

### ISSUE THREAD

**Issue by FatalCatharsis** [Swagger2Markup/swagger2markup#366]
Thanks for raising a Swagger2Markup issue. Please provide a brief description of your problem along with the Swagger2Markup version you are using. If possible, please also consider putting together a complete Swagger specification that reproduces the issue. It's better if the Swagger specification is small and isolate the issue.

Swagger2Markup version:
1.3.1

Problem description:
I use this plugin to create markdown files that I version with the source of my project explaining how to use the rest service. It works fine, but subsequent runs reorder parameters. Without any changes to my source, whenever I build my project, the markdown generates differently and it shows up as changes.

A few examples of diffs:

![60044489-1abfb200-9688-11e9-839e-83d000b8bdc7](https://user-images.githubusercontent.com/2822917/61558649-433f8f80-aa2d-11e9-9ac6-0b3da6bbaf06.png)

Can a change be made or a flag added to enforce ordering of parameters so that the generated markdown doesn't change unless I make a substantive change to my source?

**Comment by RobWin** [comment]
You can set the property `swagger2markup.parameterOrderBy=NATURAL`
