### ISSUE TITLE
No plugin found for prefix 'asciidoctor' in the current project and in the plugin groups

### ISSUE THREAD

**Issue by zhongql** [Swagger2Markup/swagger2markup#367]
Swagger2Markup version:  1.3.3

Problem description:
I was use swagger2markup and  swagger2markup-maven-plugin to generated Docs. But could't work, the error was " No plugin found for prefix 'asciidoctor' in the current project and in the plugin groups". How should I solve it?

**Comment by austek** [comment]
@zhongql is this still an issue?
