### ISSUE TITLE
The PDF can't contain an enumeration with too many types describe

### ISSUE THREAD

**Issue by LPhilibert** [Swagger2Markup/swagger2markup#375]
<img width="316" alt="Cap2_issueflou" src="https://user-images.githubusercontent.com/50821629/68116026-1f2f8d80-fefa-11e9-9a39-37b02e3afa3f.PNG">
<img width="315" alt="Cap1_issueflou" src="https://user-images.githubusercontent.com/50821629/68116027-1fc82400-fefa-11e9-8224-918fe4bf479e.PNG">

Swagger2Markup version: 1.3.7

Problem description:
When an enumeration contains too many types, it goes beyond the box area of the variable and continue on the next pages underneath the main description's board.

**Comment by RobWin** [comment]
What is your suggestion?
