### ISSUE TITLE
Cannot find SwaggerParser Why?

### ISSUE THREAD

**Issue by StarPxc** [Swagger2Markup/swagger2markup#377]
Thanks for raising a Swagger2Markup issue. Please provide a brief description of your problem along with the Swagger2Markup version you are using. If possible, please also consider putting together a complete Swagger specification that reproduces the issue. It's better if the Swagger specification is small and isolate the issue.

Swagger2Markup version:1.3.3

Problem description:
I need to use swagger2markup on the intranet. I copy all jar packages into the intranet, but when I run, I report a **NoClassDefFoundError** because the **SwaggerParser** class is not found. After debugging the Internet, it was found that **SwaggerParser** does not exist under **io.swagger.parser**. So I wonder where this class is and how to import it.

**Comment by austek** [comment]
@StarPxc what do you mean by copying file to the intranet? Do you have a sample project that can reproduce the problem?
