### ISSUE TITLE
Missing format for arrays

### ISSUE THREAD

**Issue by ejain** [Swagger2Markup/swagger2markup#38]
Given the following Swagger spec for a parameter:
```json
"schema": {
  "type": "array",
  "items": {
    "type": "string",
    "format": "byte"
  }
}
```

...I'd expect the generated docs to show something like "string (byte) array", but I get "string array".

**Comment by RobWin** [comment]
The Format should be shown if it is in the Swagger Model generated by [swagger-parser](https://github.com/swagger-api/swagger-parser). If the Format is missing, it might be a missing feature in the parser. Please open an issue in the other project.

**Comment by ejain** [comment]
The "format" is present in the Swagger spec passed to [Swagger2MarkupConverter.fromString](https://github.com/Swagger2Markup/swagger2markup/blob/master/src/main/java/io/github/robwin/swagger2markup/Swagger2MarkupConverter.java#L101).

**Comment by RobWin** [comment]
Also in the Java Swagger Model object created by the swagger-parser?
Unfortunately I can't debug it in the next days, because Iam still on parental leave. I will have a look at it as soon as I can.

**Comment by RobWin** [comment]
I created an example and debugged it:
```
  "pictures": {
      "type": "array",
      "items": {
              "type": "string",
              "format": "byte"
       }
   }
```

Swagger2Markup uses the official swagger-parser to parse the JSON into a Java Model representation. But the `format` is null in the `pictures` array. Seems to be a missing feature in the swagger-parser.

![image](https://cloud.githubusercontent.com/assets/5815046/10040302/a1a8d436-61da-11e5-9f15-ea3a7a0a521a.png)

**Comment by RobWin** [comment]
Thx for creating the issue.

**Comment by fehguy** [comment]
Hi, assuming the parameter in example https://github.com/Swagger2Markup/swagger2markup/issues/38#issue-107645636 is of type `body`, this is verified working:

https://github.com/swagger-api/swagger-parser/commit/8162a8287b500ee2064c8c17374ffe6bed9c2672

**Comment by RobWin** [comment]
I tested it as a property of a model definition not as the body schema directly.

**Comment by RobWin** [comment]
Which one do you mean @ejain? Body parameter or property of model definition?
