### ISSUE TITLE
I hope converting to .doc

### ISSUE THREAD

**Issue by stromyin** [Swagger2Markup/swagger2markup#406]
Thanks for raising a Swagger2Markup issue. Please provide a brief description of your problem along with the Swagger2Markup version you are using. If possible, please also consider putting together a complete Swagger specification that reproduces the issue. It's better if the Swagger specification is small and isolate the issue.

Swagger2Markup version:

Problem description:
I hope converting to .doc

**Comment by RobWin** [comment]
Hope is always good ;)

**Comment by austek** [comment]
I believe such a feature will be out-of-scope for this project. However, asciidoc can be used to achieve that. please check https://github.com/asciidoctor/asciidoctor/issues/3481
