### ISSUE TITLE
Paths Index

### ISSUE THREAD

**Issue by merravid** [Swagger2Markup/swagger2markup#407]
Using the cli tool, is it possible to generate a paths index before the individually detailed paths? This would be useful for users of the API to get a quick overview, especially for large and complex APIs.

If this functionality is not alredy available, I can have a go at implementing it.

**Comment by RobWin** [comment]
It's not yet available.

**Comment by RobWin** [comment]
What do you mean by path index? A ToC which shows the paths?

**Comment by RobWin** [comment]
You can group paths by tags and then use `swagger2markup.pathsGroupedBy = TAGS`

**Comment by merravid** [comment]
Yes, a ToC of all the paths. Does .pathsGroupedBy achieve this?

**Comment by RobWin** [comment]
Do you convert to AsciiDoc? Then there should be a ToC like this: 
https://github.com/Swagger2Markup/swagger2markup/blob/master/swagger2markup-documentation/src/docs/asciidoc/images/Swagger2Markup.PNG

**Comment by merravid** [comment]
Yes I convert to AsciiDoc, then open the AsciiDoc in AsciiDocFX and convert to HTML.

I don't get the left TOC panel. I only get the main content. What am I missing?

**Comment by merravid** [comment]
[This issue seems related](https://github.com/Swagger2Markup/swagger2markup-cli/issues/24)

**Comment by tntclaus** [comment]
@merravid to get table of contents u need to add `:toc:` argument to the document header. Then asciidoctor (or other software that supports `:toc:` argument) will generate it for you.  

See https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#table-of-contents-toc

**Comment by merravid** [comment]
@tntclaus That worked like a charm! Thanks!
