### ISSUE TITLE
References Not Recognized in Response

### ISSUE THREAD

**Issue by tschaible** [Swagger2Markup/swagger2markup#41]
Using the Swagger 2.0 spec, if i have a set of global responses as follows:

    responses:
      Not Found:
        description: Not Found
        schema:
          type: object
          $ref: '#/definitions/Error'
  
and then reference them later in a path as follows:

      responses:
        '400':
          $ref: '#/responses/Bad Request'

I get the following output (asciidoc)

    ==== Responses
    [options="header"]
    |===
    |HTTP Code|Description|Schema
    |400|null|No Content
    |===

It would be great if the referenced response was picked up, and the description and the schema were included in the output.

**Comment by RobWin** [comment]
Hi, references do work. Could you please provide a full Swagger example which does not work?

**Comment by RobWin** [comment]
Ah ok. Its a new feature in the swagger-parser.
http://github.com.proxy.parle.co/swagger-api/swagger-core/issues/1436

I have to update to the newest swagger-core and swagger-parser.

**Comment by tschaible** [comment]
Simple Swagger Example showing this below (if it's still helpful):

```
swagger: '2.0'
info:
  version: 0.0.0
  title: 'Sample Response References'
responses:
  Not Found:
    description: Not Found
    schema:
      $ref: '#/definitions/Error'
paths:
  /persons:
    get:
      description: |
        Gets `Person` objects.
        Optional query param of **size** determines
        size of returned array
      parameters:
        - name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      responses:
        '200':
          description: Successful response
          schema:
            title: ArrayOfPersons
            type: array
            items:
              title: Person
              type: object
              properties:
                name:
                  type: string
                single:
                  type: boolean
        '404':
          $ref: '#/responses/Not Found'
definitions:
  Error:
    properties:
      statusCode:
        type: integer
        description: The HTTP Status Code
      reason:
        type: string
        description: The HTTP Reason message
```

And then the output ends up as
```
== Paths
=== GET /persons
==== Description
:hardbreaks:
Gets `Person` objects.
Optional query param of **size** determines
size of returned array


==== Parameters
[options="header"]
|===
|Type|Name|Description|Required|Schema|Default
|QueryParameter|size|Size of array|true|number (double)|
|===

==== Responses
[options="header"]
|===
|HTTP Code|Description|Schema
|200|Successful response|object array
|404|null|No Content
|===
```

**Comment by tschaible** [comment]
Additionally, looking a bit more into the details, it seems like there would likely be 2 different ways of implementing this.  I'm curious which would be implemented (or another I haven't mentioned).

# Responses Section
Similar to how Definitions gets a section, Responses would get a section, and each Response referenced in a path would be a simple link for AsciiDoc to the appropriate Response in the Responses section.

This seems consistent with how things are handled for Models and Parameters, which reference Definitions.

# Responses Lookup
Whenever a Response is referenced, the Description/Type would be retrieved from the referenced Response and placed directly in the table.

This would be a departure from the current approach.

**Comment by RobWin** [comment]
Hi, correct analysis.
I plan to implement the "Responses section".

**Comment by tschaible** [comment]
As a further note, I was trying to get a minimal approach working for my current needs.

I believe swagger-parser has a bug in it that would need to be addressed before you could implement any changes in swagger2markup.

I've opened up an issue and PR which you can find here: https://github.com/swagger-api/swagger-parser/issues/122

**Comment by RobWin** [comment]
Thx for your work.
Do you plan to create a PR for Swagger2markup?

**Comment by tschaible** [comment]
Sure, I think I've got a pretty good handle on how everything pieces together now, and I can take a stab at it.

I'll wait on opening anything for now until the issue in swagger-parser gets resolved, but I can get everything prepped in my fork.

**Comment by RobWin** [comment]
Sounds great. :)

**Comment by RobWin** [comment]
Any news?

**Comment by tschaible** [comment]
My day job's been keeping me a bit busy last week and this week.  I'll try and carve out some time this weekend.

I did the initial setup, and upgraded dependencies to the latest development version of swagger-parser, but one of the unit tests was failing.  I want to investigate and make sure everything is stable before continuing.

It does look like as of today, swagger-parser has done a new release which included my fix, so the upstream stuff should be ready now.

**Comment by RobWin** [comment]
Same here. My day job is keeping me too busy.
Thank you for your efforts.

**Comment by RobWin** [comment]
I'm on it now

**Comment by RobWin** [comment]
Could you please test v0.9.0, if it works for you?

**Comment by tschaible** [comment]
I'm still having a few issues on my larger project.

In my actual specification, I have multiple referenced responses (usually for 400,401,500).  401 shows up as expected now, but 400 and 500 still show up as null/No Content.

Debugging a bit more, in the Swagger object itself, 400/500 are listed as RefResponse objects while 401 is converted to a Response.  I didn't see any specific changes in swagger2markup beyond updating to the latest swagger-parser, so I'm assuming for now it's swagger-parser that is being inconsistent.

I'll go through debugging of swagger-parser a bit more to see if I can isolate the change.

As a side question, I saw swagger2markup-maven-plugin now is in this git repo, and was updated, but didn't see it in Maven central (though the rest of the swagger2markup artifacts were there).  Can that be put into central too (for now, it's easy enough to build/deploy locally)?

Here's the Maven central search link for reference: http://search.maven.org/#search%7Cga%7C1%7Cswagger2markup

**Comment by RobWin** [comment]
Yes, it's on my to-do list to publish swagger2markup-maven-plugin to Maven/JCenter.

Regarding the references responses. I did not have to change anything in Swagger2Markup, because the new version of the swagger-parser includes the references responses automatically now.

**Comment by tschaible** [comment]
I believe I've tracked down the source for more issues, and it does appear to be in swagger-parser.

Specifically, if referenced responses contain spaces ('Not Found' instead of 'NotFound') swagger-parser won't resolve them.

It isn't 100% clear to me from specifications if spaces are even allowed in names, but I believe they are.  In either case, I'll move it over to the swagger-parser repository.

Everything else looks like it's working as expected once I remove spaces.

**Comment by RobWin** [comment]
Great. Thx

**Comment by tschaible** [comment]
For reference, the swagger-parser issue on spaces is

https://github.com/swagger-api/swagger-parser/issues/137

and the PR is

https://github.com/swagger-api/swagger-parser/issues/138
