### ISSUE TITLE
How To: Sample Request Response

### ISSUE THREAD

**Issue by raDiesle** [Swagger2Markup/swagger2markup#42]
What is your recommandation to do this?

Just include json manual ( the ones we use in the integr. tests) ?
I know that there is some support for generating request response out of Junit tests,
but how to use with swagger2markup ?

**Comment by RobWin** [comment]
Which tech stack do you use?
Spring, Springfox? Or Jax-Rs?
Java or JavaScript?

I personally use Spring MVC and [Spring Restdocs](https://github.com/spring-projects/spring-restdocs) to generate snippets. Have a look at https://swagger2markup.readme.io/docs/spring-restdocs and the demo https://github.com/Swagger2Markup/spring-swagger2markup-demo

If you use Swagger2markup, I would love to get your GitHub Star.

**Comment by raDiesle** [comment]
Hi Robin,
thx for quick reply. Seems like my question was too easy.
I started with Springfox this time, because the techstack is based on Spring MVC. 

By the way: it was kind of frustating for my colleague, how to generate swagger.json, because none of the tests demonstrates how to generate this end2end, but I could helped out.

Alright, thanks for your statement, Restdocs we'll switch to and pass same json we use for integrationTests as Request

**Comment by RobWin** [comment]
The demo shows how to use Spring MVC, Springfox and Swagger2markup end2end with Gradle.
