### ISSUE TITLE
swagger2markup-cli 1.3.4 jar is missing in maven central

### ISSUE THREAD

**Issue by chenrui333** [Swagger2Markup/swagger2markup#433]
👋  just a reminder that Swagger2Markup 1.3.4 jar does not exist in maven central. Thanks!

**Comment by ShubhamRwt** [comment]
Hello @chenrui333, Are you talking about this --> https://search.maven.org/search?q=g:io.github.swagger2markup

**Comment by ShubhamRwt** [comment]
I can see the the new 1.3.4 under maven repository also -->https://mvnrepository.com/artifact/io.github.swagger2markup/swagger2markup , and I am also able to download jar from there

**Comment by chenrui333** [comment]
I was referring to this one, https://repo1.maven.org/maven2/io/github/swagger2markup/swagger2markup-cli/

**Comment by chenrui333** [comment]
update my issue title to avoid confusion.

**Comment by ShubhamRwt** [comment]
Actually I haven't made a new release for the swagger2markup cli yet, only the new release for swagger project is out

**Comment by ShubhamRwt** [comment]
So its not exactly missing, the bits related to the swagger2markup projects are out, on the other hand swagger2markup cli is a different project

**Comment by ShubhamRwt** [comment]
@chenrui333 I hope it answers your question

**Comment by chenrui333** [comment]
I see, that makes sense. 😅  Thanks for clarifying so responsively!
