### ISSUE TITLE
Inline schemas support

### ISSUE THREAD

**Issue by Kabhal** [Swagger2Markup/swagger2markup#52]
It seems inline schemas are not as detailed as references to global definitions.

The following swagger both reference inline schemas (Request and Response) and a global definition (ComplexObject) :
```
swagger: "2.0"
info:
  title: Test
paths:
  /path1:
    post:
      description: Path 1
      tags:
        - all
      parameters:
        - name: Request
          in: body
          schema:
            type: object
            properties:
              param1:
                description: Param 1
                $ref: '#/definitions#ComplexObject'
              param2:
                description: Param 2
                type: string
      responses:
        200:
          description: Response
          schema:
            type: object
            properties:
              generatedId:
                description: Generated id
                type: string
definitions:
  ComplexObject:
    type: object
    properties:
      volumeId:
        description: Volume id
        type: string
```

The result is :
![testschema](https://cloud.githubusercontent.com/assets/6772693/12581059/8ca6f7f4-c434-11e5-93d6-363e885321f1.png)

The schema of Request and Response is just "object".

I propose to add a local section "Definitions" to each path, next to "Description", "Parameters" and "Responses" sections.
Then, detail local objects (like in the global definitions), and create a local cross-reference to them :

![testschemawithlocaldefinitions](https://cloud.githubusercontent.com/assets/6772693/12581381/7d13a614-c436-11e5-9f7e-6e35e6147e1b.png)

One problem, though, is with the link to the local definition, because local parameters names are not globally unique.

**Comment by RobWin** [comment]
Yes, good idea.

**Comment by RobWin** [comment]
At the moment,  I'm very busy. If this is an important feature for you, feel free to create a PR.

**Comment by RobWin** [comment]
See PR #54

**Comment by Kabhal** [comment]
@RobWin I have an issue with $ref resolution, perhaps you have a tip :

Given the swagger :
```
swagger: "2.0"
info:
  title: API
paths:
  /LaunchCommand:
    post:
      summary: LaunchCommand
      description: <description>
      tags:
        - All
      parameters:
        - $ref: './relativeRef.yaml#/parameters/Reservation'
        - name: body
          description: This is the body payload
          in: body
          schema:
            type: object
            properties:
              location:
                $ref: './relativeRef.yaml#/definitions/Location'

      responses:
        200:
          description: ref
          schema:
            $ref: './relativeRef.yaml#/definitions/Location'
        201:
          description: object with ref property
          schema:
            type: object
            properties:
              location:
                $ref: './inlineSchema.yaml#/definitions/Location'

parameters:
  Reservation:
    name: reservation
    in: query
    type: boolean


definitions:
  ExternalLocation:
    $ref: ./relativeRef.yaml#/definitions/Location

  Location:
    type: object
    properties:
      Loop:
        type: boolean
```

The swagger parser returns RefProperty with format='INTERNAL' and simpleRef='Location' for all refs except for the 201 response.
The location ref in the 201 response is identified as a RefProperty with format='RELATIVE' and simpleRef='./inlineSchema.yaml#/definitions/Location'. I can't do anything with that.

Have I missed something in the spec ?

**Comment by Kabhal** [comment]
I created an issue in swagger-parser : https://github.com/swagger-api/swagger-parser/issues/177

**Comment by RobWin** [comment]
Thx

**Comment by RobWin** [comment]
Why do you use the relative path? `./relativeRef.yaml`
Testing purpose?
You can also just use `#/definitions/Location`

**Comment by Kabhal** [comment]
Yes, and it works correctly with a simple internal ref.
But we have a use case with relative paths for definitions ;)

**Comment by RobWin** [comment]
@Kabhal Do you want to joint the gitter chat room?https://gitter.im/Swagger2Markup/swagger2markup
