### ISSUE TITLE
Paths should always be sorted when not displayed "as-is"

### ISSUE THREAD

**Issue by Kabhal** [Swagger2Markup/swagger2markup#57]
I propose to introduce custom comparators to sort all resources :
- paths
- definitions
- tags
- path methods

Default ordering is set to Ordering.natural() by default.
Swagger as-is ordering is possible setting comparator to null

**Comment by RobWin** [comment]
Implemented in #58

**Comment by Kabhal** [comment]
paths and methods sorter have been merged in a single operation sorter in #67
