### ISSUE TITLE
Add support of Response Headers

### ISSUE THREAD

**Issue by arondeau** [Swagger2Markup/swagger2markup#60]
Hi there!

When I add @ResponseHeaders to my classes, their documentation do not show up in the generated markup. 

For example: 

```
    @ApiResponses(value = {
            @ApiResponse(
                    code = 201, message = "My message",
                    responseHeaders = {
                            @ResponseHeader(
                                    name = "Location",
                                    description = "The Location Header value")
                    })
    })
  ... etc.
```

Should this add a new column in the Responses table?

Thanks so much for your help and awesome library. Other than this we love it!

**Comment by RobWin** [comment]
Which library do you use to generate the Swagger file? Springfox or another lib?

**Comment by RobWin** [comment]
If you like Swagger2markup, I would love to get your GitHub Star :)

**Comment by RobWin** [comment]
Anything New?

**Comment by nrekretep** [comment]
Hi! I have a similar issue. We handcrafted our swagger api spec and the response headers are also not included in the generated asciidocs.

**Comment by RobWin** [comment]
Sry. I have misread the issue. Response headers are not rendered in v0.9.2 yet.

**Comment by RobWin** [comment]
See https://github.com/Swagger2Markup/swagger2markup/blob/master/src/main/java/io/github/robwin/swagger2markup/builder/document/PathsDocument.java#L684
Its not difficult to implement. If you have time, feel free to create a PR. 

If you use Swagger2markup, I would like to get your GitHub Star.

**Comment by RobWin** [comment]
Working on it.

**Comment by RobWin** [comment]
Implemented in the upcoming v1.0.0

**Comment by RobWin** [comment]
Looks like this:

![image](https://cloud.githubusercontent.com/assets/5815046/13674148/b7f9ecb6-e6dc-11e5-9f27-8a80f95f2cfe.png)

**Comment by nrekretep** [comment]
Looks good. You rock \m/ !

When will version 1.0 be released?

On Thu, Mar 10, 2016 at 4:25 PM, Robert Winkler <notifications@github.com>
wrote:

> Looks like this:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/5815046/13674148/b7f9ecb6-e6dc-11e5-9f27-8a80f95f2cfe.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Swagger2Markup/swagger2markup/issues/60#issuecomment-194903781>
> .
>



-- 
Peter Kern
Galgengraben 15
90574 Roßtal

E: peter@nomagic.net
W: http://www.nomagic.net
M: 0151 / 12 01 73 30
V: 09127 / 70 90 00 (Sipgate)
T: 09127 / 57 06 48 (T-Com)

**Comment by RobWin** [comment]
The SNAPSHOT is already available, but the extension SPI will change before I release it.
Do you use a Maven/Gradle plugin or Swaggger2Markup directly?

**Comment by RobWin** [comment]
Would love to get your GitHub Star as a Thanks :)

**Comment by RobWin** [comment]
Ups, just saw a minor bug in the SNAPSHOT which I have to fix tomorrow.
https://github.com/Swagger2Markup/swagger2markup/blob/master/src/main/java/io/github/robwin/swagger2markup/internal/document/builder/PathsDocumentBuilder.java#L744

**Comment by RobWin** [comment]
The following link describes how to get the SNAPSHOT
http://swagger2markup.github.io/swagger2markup/1.0.0-SNAPSHOT/#_getting_started

**Comment by nrekretep** [comment]
Here you are, you got my star.

I'll try the snaphot version.
I use the maven plugin and the cli.

**Comment by RobWin** [comment]
Maven Plugin and Cli are not updated yet. That's my task for the next days.
