### ISSUE TITLE
Refactor separated documents logic to support inter-document cross-references

### ISSUE THREAD

**Issue by Kabhal** [Swagger2Markup/swagger2markup#61]
Context :
Currently, s2m supports all-in-one document (.asString) or 3 (overview+paths+definitions) documents (.intoFolder() ).
Some extra options (.withSeparatedDefinitions, withSeparatedPaths) create "supplementary" documents without impact on others documents.

Functional :
I'd like cross-references to become inter-documents cross-references, when I generate multiple documents.
This way, AsciiDoc will continue to work as currently when 3 documents are included in a single one. But the links will work too when documents will be independently rendered as multiple HTMLs files.

Problem :
Generated cross-references can only address one generation model at a time :
- all-in-one : all cross-refs are local
- 3 documents : cross-refs to definitions are Xrefs to ./definitions.adoc
- separated definitions : cross-refs to definitions are Xrefs to each generated definition file

Proposal :
For consistency, when using separated files (withSeparatedDefinitions or withSeparatedPaths), we should not generate original paths.adoc and definitions.adoc files, and Xrefs are always inter-document XRefs to each definition file.
If you want to generate the 3 docs too, you'll have to relaunch the builder with different options.

Corollary:
When using Markdown output, all Xrefs should be disabled in all modes except the all-in-one mode (.asString() ) because Markdown does not support inter-documents Xrefs.

**Comment by RobWin** [comment]
Sounds great. That's fine with me.

**Comment by Kabhal** [comment]
In fact, AsciiDoc[tor] automatically transforms inter-document cross-references to cross-references if it detects the target document has been included.

The point here is that inter-document cross-references is an AsciiDoctor extension to original AsciiDoc spec, I don't know what will be the result with the Python AsciiDoc implementation, for example.

**Comment by RobWin** [comment]
Let's focus on AsciiDoctor's AsciiDoc features and GitHub Flavored Markdown features :)

**Comment by Kabhal** [comment]
ok ..
