### ISSUE TITLE
Cross-reference in Security subsection of a path element refers to invalid Security Section 's anchor

### ISSUE THREAD

**Issue by rostskadat** [Swagger2Markup/swagger2markup#65]
2 problems:

- It seems that the [PathsDocument.securitySchemeSection()](https://github.com/Swagger2Markup/swagger2markup/blob/master/src/main/java/io/github/robwin/swagger2markup/builder/document/PathsDocument.java#L590) does not generate the proper cross-reference. This cross-reference points to the Security Section of the corresponding name. The anchor is generated with an underscore while the cross-reference is not.
- Furthermore the code does not seem to work properly when generating several documents, as the cross-reference always point to the same document (the current one).

**Comment by RobWin** [comment]
Only 0.9.3-SNAPSHOT is currently affected.

**Comment by RobWin** [comment]
Did you add a testcase which shows this issue? Could you please provide me an example Swagger file?

**Comment by RobWin** [comment]
You bug is in this line: https://github.com/Swagger2Markup/swagger2markup/blob/master/src/main/java/io/github/robwin/swagger2markup/builder/document/PathsDocument.java#L607
The first parameter of docBuilder.crossReferenceAsString is the document which contains the security definitions. Atm the document name is is equal to the security key
