### ISSUE TITLE
Optionally isolate body display from other parameters

### ISSUE THREAD

**Issue by Kabhal** [Swagger2Markup/swagger2markup#73]
I propose to introduce an option to change the way body parameter is displayed.
The display is more friendly and well-spaced for APIs with a lot of operations using body parameters.

---
Before :
![original](https://cloud.githubusercontent.com/assets/6772693/13052498/78209bfc-d3ff-11e5-98aa-b75d827e0f54.png)

---
After :
![isolatedbody](https://cloud.githubusercontent.com/assets/6772693/13106679/d8e8054a-d569-11e5-81f8-4c7b4a49d507.png)

**Comment by RobWin** [comment]
Could you please also paste a screenshot of the current state?

**Comment by RobWin** [comment]
You mainly need more space to add a long description to a body parameter?

**Comment by Kabhal** [comment]
it's an extra bonus, but it is not the main goal.
the main goal is to add some clarity in the presentation for APIs which use a lot of body parameters (RPC apis for example ;) )

**Comment by RobWin** [comment]
I agree. I also think that in REST-based APIs the BodyParameter should be more eye-catching.

**Comment by RobWin** [comment]
I think in the flatBody layout its not directly clear which body parameter the root object of the body is (exception of the name *RequestParam). You have to look at the properties of the objects. The inline parameters could also be sorted naturally.
The table layout is more clear about that.
What do you think?

**Comment by Kabhal** [comment]
Target screenshot updated : the root object is at top, and is not titled.
