### ISSUE TITLE
External folder path consistency

### ISSUE THREAD

**Issue by Kabhal** [Swagger2Markup/swagger2markup#80]
Currently : 
Paths descriptions are in :
```
swagger2MarkupConfig.getDescriptionsFolderPath() + "/paths/<operation>/description.{adoc,md}" ;
```
Paths examples are in :
```
swagger2MarkupConfig.getExamplesFolderPath() + "/<operation>/<example>.{adoc,md}";
```

Definitions schemas are in :
```
swagger2MarkupConfig.getSchemasFolderPath() + "/<definition>.{json,xml}";
```

We should manage external paths consistently.

I propose :
```
swagger2MarkupConfig.getDescriptionsFolderPath() + "/operations/<operation>/description.{adoc,md}";
swagger2MarkupConfig.getExamplesFolderPath() + "/operations/<operation>/<example>.{adoc,md}";
swagger2MarkupConfig.getSchemasFolderPath() + "/definitions/<definition>/schema.{json.xml};
```

By default, we could set swagger2MarkupConfig.getDescriptionsFolderPath, swagger2MarkupConfig.getExamplesFolderPath and swagger2MarkupConfig.getSchemasFolderPath to swaggerFile.getParent()

This breaks back-compatibility.

**Comment by Kabhal** [comment]
An alternative proposal :
```
swagger2MarkupConfig.getDescriptionsFolderPath() + "/<operation>/description.{adoc,md}";
swagger2MarkupConfig.getExamplesFolderPath() + "/<operation>/<example>.{adoc,md}";
swagger2MarkupConfig.getSchemasFolderPath() + "/<definition>/schema.{json.xml};
```

The user have more options to decide where his files are stored, but he'll probably have to configure all paths manually instead of using the proposed swaggerFile.getParent() defaulting.

**Comment by Kabhal** [comment]
Which one do you prefer ? :)

**Comment by RobWin** [comment]
I prefer
```
swagger2MarkupConfig.getDescriptionsFolderPath() + "/<operation>/description.{adoc,md}";
swagger2MarkupConfig.getExamplesFolderPath() + "/<operation>/<example>.{adoc,md}";
swagger2MarkupConfig.getSchemasFolderPath() + "/<definition>/schema.{json.xml};
```

**Comment by Kabhal** [comment]
Then, for example in extension implementation, I'll have to create .withOperationExtensions() and .withDefinitionExtensions() to be able to specify different input directories. Ok ?

**Comment by RobWin** [comment]
Some external files could be written by hand (src/docs/asciiDoc) and some files could be generated by another tool (build/docs/asciiDoc). I think one root folder is not sufficient.

**Comment by RobWin** [comment]
But we could define default folder conventions
