### ISSUE TITLE
Pluggable extension support

### ISSUE THREAD

**Issue by Kabhal** [Swagger2Markup/swagger2markup#83]
We want to introduce some new extension points to Swagger2Markup to extend features.

We provide :
- an *ExtensionRegistry* to register user extensions
- an *Extension* root interface
- several extension points to extend :
  - SwaggerExtension : update Swagger base model
  - DefinitionsContentExtension : append content to "definitions" document
  - DefinitionContentExtension : append content to a definition
  - PathsContentExtension : append content to "paths" document
  - OperationContentExtension : append content to an operation
  - OverviewContentExtension : append content to "overview" document
  - SecurityContentExtension : append content to "security" document

Extensions will be applied in registering order for a given extension category.

**Comment by RobWin** [comment]
:+1:

**Comment by RobWin** [comment]
I would think about a way to register extensions like this:

`Swagger2MarkupConfig.ofDefaults().registerExtension(new MySwaggerExtension())`

**Comment by Kabhal** [comment]
We manage extensions consistently we configuration :

```
registry = Swagger2MarkupRegistry.ofDefaults().withExtension(new MySwaggerExtension(myOwnImportantObject)).build()
config = Swagger2MarkupConfig.ofDefaults().with...().build()

Swagger2MarkupConverter().withConfig(config).withRegistry(registry).build()
```
