### ISSUE TITLE
Move SpringRestDocs examples to extension

### ISSUE THREAD

**Issue by Kabhal** [Swagger2Markup/swagger2markup#91]
Currently, withExamples triggers  :
- auto-generated request samples from Swagger models
- SpringRestDocs (http-request.<ext>, http-response.<ext>, curl-request.<ext>

We want to implement anything not from Swagger model to extensions, so we want to move SpringRestDocs examples to a proper extension.

**Comment by RobWin** [comment]
Maybe we should rename the RestDocs extensions to `SpringRestDocsOperationsContentExtension`

**Comment by RobWin** [comment]
The new one could be `GeneratedExamplesOperationsContentExtension` ?

**Comment by RobWin** [comment]
Folder names should have snake_case instead of lowercase :dancers:

**Comment by Kabhal** [comment]
Fixed in https://github.com/Swagger2Markup/swagger2markup/commit/b272e812d06256f39f808355333bd2f50b2a2944
